### ISSUE TITLE
Backup codes generator gives integers instead of strings

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-mfa#111]
Due to the way PHP iternally handles array keys, string keys that consist purely of digits (i.e. that represent a valid integer) are converted to index entries in the array, that is the string is converted to an integer.

Due to duck typing the code base currently does not seem to have much of an issue with this, apart from the odd failing test where a digit only generation is produced.
See: https://travis-ci.com/silverstripe/silverstripe-mfa/jobs/196520285#L643

This is replicable in a unit test shown: https://github.com/silverstripe/silverstripe-mfa/compare/master...creative-commoners:heres-my-number-so-error-maybe

Although this _probably_ won't cause any issues as is, the intermittently breaking unit test is annoying, and we cannot rule out this ever happening in user code. I feel we should find a better way to supply backup codes to the user than as keys in an array.

Potential solutions might include:
- flipping the array, so the hash is the key. But this relies on a hash also never being entirely numeric.
- having a keyed entry for each code, e.g. `['code' => ..., 'hash' => ...]`
- something else entirely.

**Comment by robbieaverill** [comment]
I wondered whether we should have a state encapsulation object for returning this stuff, but I think all we need to do here is replace the use of `array_combine()` with something that doesn't coerce `0123` to `123`

**Comment by ScopeyNZ** [comment]
The problem is no matter how you set the key of an array `'123'` will always become `int(123)`.

**Comment by NightJar** [comment]
`0123` is actually safe, almost ironically. It will remain a string.
`"123"` will become `123` however.

**Comment by robbieaverill** [comment]
What's the problem with that?

**Comment by ScopeyNZ** [comment]
I think it's specifically about return type handling. The tests occasionally break because the key that you expect to be a string is an integer.

**Comment by NightJar** [comment]
> What's the problem with that?

Please [see the provided link](https://travis-ci.com/silverstripe/silverstripe-mfa/jobs/196520285#L644)

**Comment by robbieaverill** [comment]
Right, I'll add a state encapsulation return instead

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-mfa/pull/112
