### ISSUE TITLE
Remove dependency on SiteConfig (and admin)

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-mfa#113]
We are currently building this module to be compatible with `silverstripe/siteconfig` in order to allow an admin to configure their site from the CMS - and with `silverstripe/admin` in regards to viewing a members MFA configuration - and allowing members to alter their configuration.

However as SilverStripe is usable without Admin (and thus without SiteConfig) I think it would be best to allow site wide MFA configuration from YAML, as technically it is still possible for Members to log in, even without the admin interface to log into.

**Comment by robbieaverill** [comment]
To be honest, I don't think this has enough value to warrant the complexity that it would bring right now. Let's reopen in future if somebody really wants this.

**Comment by NightJar** [comment]
This is necessary as our very first integration project requires it.

**Comment by robbieaverill** [comment]
cc @silverstripeux - FYI we will need to make the "Enable MFA in the CMS" settings in the "Settings" section also configurable by developers in YAML

**Comment by NightJar** [comment]
Integration project defines it as per group requirements, if I'm recalling correctly.
i.e. A user belongs to many groups, and if _any_ of those groups require MFA, then they're required to authenticate with MFA (highest level of security is applied to the user).

**Comment by robbieaverill** [comment]
Yeah that's true, we can raise a separate issue for that though - let's keep requirements separate

**Comment by NightJar** [comment]
Yeah for sure, just providing a little more clarity on the level of abstraction/decoupling that needs to be present for that to be easy :)

**Comment by robbieaverill** [comment]
"Group based MFA settings" can be treated separately, we won't be doing this issue though
