### ISSUE TITLE
Create configuration for mandatory MFA methods

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#12]
By default backup codes should be mandatory, but configuration should be available to developers to set this to null or change to another method.

**Comment by brynwhyman** [comment]
We might need a bit more thought on designs if other MFA methods can be set to mandatory. Should this mean that a mandatory method (other than back up codes) shouldn't be displayed next to an alternative method to select for registering?

I.e If TOTP is set as a mandatory method, it seems unjust to display that next to a another method to select for registering, if the other option is not mandatory

**Comment by ScopeyNZ** [comment]
Superseded by #31
