### ISSUE TITLE
Add back up code method - registration frontend

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-mfa#13]
Backend work implemented in #4

ACs
- Back up codes are generated after the successful registration of a method.
- There is no confirmation of the codes required, they are simply displayed to the user once.
- Back up codes are presented in a format that can be copied to the clipboard without loosing formatting. 
- There is a button to download the codes using JavaScript.
- There is a button to copy the codes to the clipboard.
- It should look good with the Wātea theme.
- There is text describing back up codes as per the designs.
- Use generic class names for buttons.

Designs
https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/322766388

**Comment by brynwhyman** [comment]
Relevant discussions from the bootstrapmfa module here: https://github.com/Firesphere/silverstripe-bootstrapmfa/issues/14

Have a read before picking this issue up

**Comment by robbieaverill** [comment]
Done in https://github.com/silverstripe/silverstripe-mfa/pull/30
