### ISSUE TITLE
Refactor traits into service classes

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-mfa#131]
Currently traits are provided to extract functionality common across `RequestHandler`s for MFA. After discussions with the team, we think it makes more sense to provide this functionality in a service class (or several service classes).

**Comment by robbieaverill** [comment]
Do you still want to do this? I don't see a huge amount of value in it any more

**Comment by robbieaverill** [comment]
Closing, feel free to reopen if anyone feels strongly about doing it at a later stage
