### ISSUE TITLE
[Demo review] Setup up process (increase visual consistency)

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-mfa#136]
## Introduction screen
![Screen_Shot_2019-05-24_at_10_43_35-2-2](https://user-images.githubusercontent.com/8085295/58386790-20aa7f00-8059-11e9-9ab7-8a8eac37991c.png)
- [x] ~~Remove hr tag from footer (not apart of MFA but the site theme)~~
- [ ] Remove row with border-bottom above content
- [ ] Add spacing on top and bottom of title and button, respectively (40px)
- [x] Make all primary buttons green throughout all views
- [x] Make all secondary buttons white with blue text throughout all views
- [x] Add help text link as per designs

## Selection screen
![Screen_Shot_2019-05-24_at_11_25_19-fullpage-2](https://user-images.githubusercontent.com/8085295/58386731-ef7d7f00-8057-11e9-9e2f-a3494398bf3d.png)
- [ ] Add spacing around the body of content for all views (20px)
- [ ] Add spacing between imagery and text (16px)
- [x] Add Help text underneath methods 

## TOTP setup screen
![Screen_Shot_2019-05-24_at_11_31_56](https://user-images.githubusercontent.com/8085295/58386881-39fffb00-805a-11e9-887a-c0fec6b7bfbc.png)
- [x] Add help text 
- [ ] Add responsive media query for mobile view, so that all content stacks into a centre aligned single column

## Recovery codes screen
![Screen_Shot_2019-05-24_at_11_32_17](https://user-images.githubusercontent.com/8085295/58386950-125d6280-805b-11e9-8676-183ab3ace562.png)
- [x] Update help text (will be resolved via #142)

**Comment by robbieaverill** [comment]
>Add help text link as per designs

It's there already, but we don't actually have any user help documentation yet so the link is hidden until it is configured with a URL to reference

**Comment by newleeland** [comment]
Awesome @robbieaverill sounds like much of this is already done.

> > Make all secondary buttons white with blue text throughout all views
> 
> This goes against Bootstrap's defaults, which the starter theme implements. Do you want us to define our own button styles instead? https://getbootstrap.com/docs/4.3/components/buttons/

Not to define our own button styles. but look like We wouldn't want to use Starter Theme look and feel for MFA, but more of the CMS looks, as MFA is apart the CMS rather than the site. 
We'd want to try and ensure "**all**" the secondary buttons are consistent throughout the whole MFA experience. Rather having a grey secondary button on the first screen and white button on the next screen, lets just have all of them the same. I don't mind if we use the btn-secondary styling from the CMS instead of the blue text suggested above. Not sure if #135 fix this.

> > Blue/green button colours
> 
> I agree, but please be aware that we followed the designs to get what you see at the moment

Cool, as long as the all the MFA primary buttons are consistent. 

> > Update help text
> 
> May I ask why? Every other place we use these links will use the same "Find out more" text. By changing it for one screen we're adding a little more complexity to the code for questionable gain (IMO).

It was raised that using more descriptive links are a best practice for accessibility, as they give more context to the user that cannot see the visual context.

**Comment by ScopeyNZ** [comment]
> as MFA is apart the CMS rather than the site.

This is not necessarily true. The login forms we provide as part of `silverstripe/framework`. You don't need CMS to provide login. And you might choose to use the login forms we provide to manage user access to your own site.

**Comment by newleeland** [comment]
> > as MFA is apart the CMS rather than the site.
> 
> This is not necessarily true. The login forms we provide as part of `silverstripe/framework`. You don't need CMS to provide login. And you might choose to use the login forms we provide to manage user access to your own site.

True. but it would be good to have all the buttons in the flow consistent at least so that users know its that same experience.

**Comment by robbieaverill** [comment]
I'm going to close this, we can review it again towards the end of the project and log individual issues =)
