### ISSUE TITLE
Allow users to skip MFA setup - Backend

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-mfa#14]
Implement functionality so the MFA setup can be skipped

### ACs
- [ ] Functionality exists to 'skip' MFA setup after successful member login
- [ ] Skip function is available if global grace period is enabled, and it has not ended, and the user does not have a registered method already; 
- [ ] Skip function is available if MFA is not mandatory
- [ ] MFA registration will only be shown once if MFA is not mandatory, and has been skipped by the user already
- [ ] If MFA is mandatory, and the grace period hasn't ended, registration is shown each time
- [ ] No frontend work is required

**Comment by robbieaverill** [comment]
I'm going to make the following assumptions:

* We need a "can skip" API to determine whether the user can skip the MFA registration process
* We need a "should go to MFA" API to determine whether to send the user to MFA registration/login after default SS login
* Both results should be added to the API schema for the frontend app to fetch
* After default SS login, the backend should check both the "should go to MFA" value and redirect to either MFA or continue as usual

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-mfa/pull/32
