### ISSUE TITLE
[Demo review] MFA enabling process - Show current time (and minor fixes)

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-mfa#140]
![puxmfa_demo_silverstripe_cc_admin_settings_](https://user-images.githubusercontent.com/8085295/58846159-53481d80-86d2-11e9-8280-6fd72e835193.png)

### Update text changes
- [ ] Update userhelp link to "Learn about MFA" so its more accessible. 
- [ ] Update grace period label to "Allow grace period until (Optional):"
- [ ] Add help text below input: "MFA setup will be optional during grace period. Reminders to setup MFA will appear on login.

See **CMS Admin turns on 2FA**: https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/folder/components/5c68f96ffb26bb0018525d1a

**Comment by robbieaverill** [comment]
There's a semantic difference between showing the current date and not showing anything at all. By showing the current date, you'll end up setting the grace period to expire today, which is different from not setting one at all. I think if you want to do this you might want to also have a checkbox saying "Grace period enabled" to clarify that the date you set (e.g. today) is actually enforced.

**Comment by robbieaverill** [comment]
@newleeland would you be happy to skip the "show current date/time" suggestion? I'm happy with the rest of your suggestions

**Comment by newleeland** [comment]
I'm fine with not showing the current time and just havd "dd/mm/yyyy"
I'll be updating the design to have the text label t include "(Optional)" in the end

**Comment by newleeland** [comment]
Potential text:
Will be Required from 
if date is in the future then user will be prompted registration to help them

**Comment by brynwhyman** [comment]
Closing this issue as tasks are now captured in other issues.

- Update userhelp link to "Learn about MFA" so its more accessible. : #142
- Update grace period label to "Allow grace period until (Optional):": #144
- Add help text below input: "MFA setup will be optional during grace period. Reminders to setup MFA will appear on login: #144
