### ISSUE TITLE
More accessible help links

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#142]
The 'Find out more' links aren't giving enough context.

We should update the link title so that the screen reader picks it up. 

This provides more context to what it's linking to. Could be a link title or new link text.

Suggested screens are here:

### Helptext links
* Learn about MFA. 
https://invis.io/F6S9NUH84AM#/326284399_CMS_-_Login_-_2FA_Enabling_-admin-_Force
* How multi-factor authentication works? 
https://invis.io/BFS7HZINRCA#/321189816_CMS_-_Setup_-_2FA_Setup_Intro
* How to use authenticator app.
https://invis.io/43SNYN9KNSP#/321189813_CMS_-_Setup_-_2FA_OTP_Setup
https://invis.io/R6SNYPLGSH2#/321189815_CMS_-_Setup_-_2FA_Setup_Selection
https://invis.io/8ESNYQGNZ67#/322766389_CMS_-_Setup_-_2FA_Verfication
* How to use security keys.
https://invis.io/R6SNYPLGSH2#/321189815_CMS_-_Setup_-_2FA_Setup_Selection
https://invis.io/M8SNYRDJHTF#/367965007_CMS_-_Setup_-_2FA_WebAuthn
* Learn about recovery codes.
https://invis.io/3ZSNYRR8K29#/322766388_CMS_-_Setup_-_2FA_Setup_Backup
* How to use recovery codes.
https://invis.io/ZYSNYSMCFQR#/351007936_CMS_-_Login_-_Sign-In_Recovery_Codes

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-mfa/pull/242
- [x] https://github.com/silverstripe/silverstripe-totp-authenticator/pull/25
- [x] https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/45

**Comment by robbieaverill** [comment]
@newleeland to clarify, are we changing each "Find out more" link to "Find out more about TOTP" and "Find out more about security keys" etc?

**Comment by newleeland** [comment]
Hey @brynwhyman can we change
**How to use authenticator app.** >> to >> **How to use authenticator apps.** 
Adding an "s" so that its consistent across the flows

**Comment by NightJar** [comment]
https://invis.io/R6SNYPLGSH2#/321189815_CMS_-_Setup_-_2FA_Setup_Selection:
* [ ]  How to use authenticator apps.
* [ ]  How to use security keys.

These two pose trouble, as there is no manner to obtain the words from outside of the modular guest context (i.e. while we're still in the host MFA component context).

>     * [ ]  Learn about MFA.
>       https://invis.io/F6S9NUH84AM#/326284399_CMS_-_Login_-_2FA_Enabling_-admin-_Force

I notice there's no counterpart to this in the Member's MFA Settings field. Is this intentional @newleeland?

>https://invis.io/ZYSNYSMCFQR#/351007936_CMS_-_Login_-_Sign-In_Recovery_Codes
>* [ ] How to use recovery codes.
The help text on this screen does not exist, nor does the prop that contains a link appear to be present on the backup code component. I will investigate further.

**Comment by NightJar** [comment]
> https://invis.io/R6SNYPLGSH2#/321189815_CMS_-_Setup_-_2FA_Setup_Selection:
> 
> * [ ]   How to use authenticator apps.
> * [ ]   How to use security keys.
> 
> These two pose trouble, as there is no manner to obtain the words from outside of the modular guest context (i.e. while we're still in the host MFA component context).

After discussing with the team, it is decided to shift translation from the front end into the PHP side in order to pass the resulting text string around as a prop.

**Comment by NightJar** [comment]
The three PRs referenced above in the timeline will close this issue.

**Comment by robbieaverill** [comment]
I added them to the issue description for you to remove ambiguity

**Comment by robbieaverill** [comment]
@NightJar there is still outstanding feedback on your TOTP pull request

**Comment by robbieaverill** [comment]
All merged
