### ISSUE TITLE
MFA is optional by default

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#144]
As a CMS owner, I don't want the ability to completely remove MFA once it's been enabled, so that I know the site will stay secure and user preferences for MFA are still respected.

AC
- Once the module is installed, MFA will be optional be default
- It is not possible through the CMS to entirely disable MFA on a site 

Notes:
- Checkbox is removed, radio button is toggled between 'optional' and 'enforced', default on optional

**Comment by newleeland** [comment]
I've updated the designs for Admin SiteConfig to accommodate this. I've
- Removed checkbox "Enable MFA for CMS access" from designs
- Updated Radio button label text.

Select **CMS Admin turns on 2FA**:
https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/folder/components/5c68f96ffb26bb0018525d1a

**Comment by brynwhyman** [comment]
There's some UI changes required as part of this issue, but speaking to @newleeland, there's some new ideas for wording. It would be good to try include this in your work to avoid rework later.

https://github.com/silverstripe/silverstripe-mfa/issues/140#issuecomment-501065709

**Comment by newleeland** [comment]
Hey @NightJar looking good. I've got a just text changes to make this clearer.

**Text changes**
![59318341-cf69e300-8d1a-11e9-8e02-de036fafe076-2](https://user-images.githubusercontent.com/8085295/59320905-422b8c00-8d24-11e9-8287-759cbedd2912.png)

Also, is there a reason why the radio labels are not aligned with radio?
