### ISSUE TITLE
Move Basic Math JS components into docs

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-mfa#147]
As we approach stabilisation, this becomes less relevant, but still worthwhile sharing with devs.

**Comment by ScopeyNZ** [comment]
I'm not sure about this. It's currently a stub for our tests. Without doing weird stuff and configuring a stub on purpose it should be pretty inert. We should probably remove the JS implementations. I think we could probably re-purpose those as docs though?

**Comment by brynwhyman** [comment]
This could follow what we do with graphql and have an 'examples' folder?

**Comment by Cheddam** [comment]
[PR here](https://github.com/silverstripe/silverstripe-mfa/pull/227)
