### ISSUE TITLE
SS3: MFA Admin UI backport

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#149]
- RegisteredMethodManagerField loads with correct information
- Modals for verification / registration of MFA methods work
- AccountReset UI works

### PR

https://github.com/silverstripe/silverstripe-mfa/pull/266

**Comment by robbieaverill** [comment]
Is this different from the "backend backport to SS3" issue?

**Comment by brynwhyman** [comment]
#153 was written to focus on the backend backport of the authentication modules. This still needs detail but I'd expect could cover back-porting the MFA app

**Comment by Cheddam** [comment]
Re-focussed this issue to cover the admin UI, as we've ended up testing and fixing the front-end UI as part of #180.

**Comment by ScopeyNZ** [comment]
See https://github.com/silverstripe/silverstripe-mfa/pull/266
