### ISSUE TITLE
SS3: Confirm standalone JS injector provides its own redux store

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#151]
- React injector provides the option of asking it to give you a redux store

**Comment by ScopeyNZ** [comment]
It doesn't. Compare:

https://github.com/silverstripe/react-injector/blob/master/src/dependency-injection/loadComponent.js#L83

with

https://github.com/silverstripe/silverstripe-admin/blob/b63a541b24611a579f98044d44e089da9c87e82d/client/src/lib/dependency-injection/loadComponent.js#L93

**Comment by robbieaverill** [comment]
So do we need to modify it so that it does, or add something else that provides Redux?

**Comment by ScopeyNZ** [comment]
Yep either of the two. I think it makes sense to be a feature of Injector though. I don't think it should be compulsory like it is currently in admin though.

**Comment by robbieaverill** [comment]
I've had a chat with @ScopeyNZ and @unclecheese about this, and we've decided that we don't actually want react-injector to provide a redux store at all - that is a concern of the admin module going forwards. More context here: https://github.com/silverstripe/silverstripe-admin/issues/836#issuecomment-506140574

New summary of where we stand (or aim to stand) with MFA and associated modules in terms of Redux and Injector:

| SS version | Area | Injector comes from | Redux comes from |
| --- | --- | --- | --- |
| 3.x | CMS | react-injector | Custom polyfill in MFA |
| 3.x | Frontend | react-injector | MFA explicitly creates one |
| 4.x | CMS | admin module | admin module via Injector |
| 4.x | Frontend | react-injector | MFA explicitly creates one |

So in terms of the SilverStripe 3.x backport, we'll need to add a snippet somewhere to the MFA codebase that provides a Redux store to the app when it's mounted, e.g.:

```diff
- <RegisteredMFAMethodListField>
+ <Provider store={createStore(...)}>
+   <RegisteredMFAMethodListField>
     { /* ... */ }
+   </RegisteredMFAMethodListField>
+ </Provider>
- </RegisteredMFAMethodListField>
```

I don't think there's much else to do for this issue now, the above example can be implemented in the "Frontend backport for SS3" issue for MFA. Do we agree with this @silverstripe/creative-commoners?
