### ISSUE TITLE
View existing backup codes in CMS

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#16]
Backend work implemented in #4

ACs
- Use the components created for the registration screen in #13 
- Codes can be viewed by selecting a `view codes` action
- Back up codes are presented in a format that can be copied to the clipboard without loosing formatting.
- There is a button to download the codes using JavaScript.
- There is a button to copy the codes to the clipboard.

Designs
https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/321186218

**Comment by brynwhyman** [comment]
We need to confirm this flow, it's not clear whether existing backup codes should be visible at any time for a user to see. 

Current designs depict backup codes being visible when a user first registers an MFA method, and not again. The only functions in the CMS profile area are to  reset backup codes.

**Comment by brynwhyman** [comment]
For now, #35 is preferred and will implemented instead of this issue

**Comment by robbieaverill** [comment]
My understanding is that we will never be able to view backup/recovery codes after the screen that initially generates and shows them to the user, which has already been implemented. Closing in favour of #35.
