### ISSUE TITLE
Ensure compatibility with external authentication services

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#160]
### Overview
It is possible for a site to provide multiple authentication services for a user:
- SilverStripe login - possibly extended by MFA
- Third party services like [RealMe](https://github.com/silverstripe/silverstripe-realme)
- LDAP (a supported module)
- SAML (not a supported module but still used in projects)

### Action
We should investigate that these authenticators can work side by side on a single installation without disruption. This probably counts out LDAP and SAML which would use MFA on top of those services.

'side by side' means you could choose to login with the SS login and MFA; or something like RealMe. That is what this issue should investigate.

### Notes
- Raising another issue to ensure that MFA works 'on top' of an LDAP authentication group: #173

**Comment by robbieaverill** [comment]
Related activedirectory and LDAP issues for this: https://github.com/silverstripe/silverstripe-activedirectory/issues/130 https://github.com/silverstripe/silverstripe-ldap/issues/25

**Comment by brynwhyman** [comment]
Closing this. More up to date actions are captured in #173
