### ISSUE TITLE
Permission limits in accessing MFA in the CMS

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#171]
### Description
I'm getting a timeout when trying to use any MFA member settings in the CMS. 

Error: `Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0`

### To recreate
1. Have a user register with TOTP on initial login
2. Attempt to add another MFA method in the CMS; or *any use any other member settings relating to MFA*
3. See that the modal defaults to register a security (identified by 'Security key' in the model title)
4. See that the modal is stuck in loading.

### Version
Testing using the recent MFA demo: https://certnzmfa2.demo.silverstripe.cc (unsure of version)

**Comment by robbieaverill** [comment]
Quick investigation looks like this may be because the user doesn't have permission to access the MFA `AdminRegistrationController`. Workaround is to add them to the administrator group in the CMS.

**Comment by brynwhyman** [comment]
Furthermore, I was able to resolve the issue if I granted the user 'Full CMS access'. It seems the resolution here should be, if the user has access to `/admin/myprofile`  they should be able to access the MFA `AdminRegistrationController`

**Comment by robbieaverill** [comment]
Reproduced using the default Content Authors group for a new user. The `admin/mfa/*` route is returning a redirect when a permission check fails.

On a side note, we should prevent this from happening and return an error instead, because this will always break when the MFA app tries to parse the (HTML) response as JSON.

**Comment by robbieaverill** [comment]
Actually, all methods in this controller already have necessary checks in place, so we can probably expose LeftAndMain permissions for the init checks to all users

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-mfa/pull/191
