### ISSUE TITLE
Create docs to describe lack of compatibility with LDAP

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#173]
It is possible for a site to use shared authentication services for a user:
- LDAP (a supported module)
- activedirectory (in limited support for SS3)
- SAML (not a supported module but still used in projects)

There will be additional work required for a site to implement MFA to be compatible with LDAP. Docs will be created to describe the limitations and guidance for proceeding. This work will not be done as part of the MFA development initiative.

### Actions
- Docs are included in the MFA module 
- Raise an issue on LDAP to highlight the incompatibility

### Pull requests

- [x] SS3: https://github.com/silverstripe/silverstripe-mfa/pull/286
- [x] SS4: https://github.com/silverstripe/silverstripe-mfa/pull/287

### Upstream issues raised

* https://github.com/silverstripe/silverstripe-activedirectory/issues/130
* https://github.com/silverstripe/silverstripe-ldap/issues/25

**Comment by ScopeyNZ** [comment]
High level assumption: this would require additional code in the modules to support it. It definitely would be additional effort though.

**Comment by brynwhyman** [comment]
Noting that there are only two stacks running the silverstripe/ldap module on our infrastructure.

**Comment by indygriffiths** [comment]
For what it's worth both Dashboards use the activedirectory module as the authenticator.

**Comment by brynwhyman** [comment]
Thanks Indy, I was going to ask about that!

**Comment by robbieaverill** [comment]
PRs at #286 and #287. Since the implementations differ slightly between SilverStripe 3 and 4 I've made two PRs instead.

> Raise an issue on LDAP to highlight the incompatibility

I've created one in each repository (activedirectory and LDAP). Does that mean we can close https://github.com/silverstripe/silverstripe-mfa/issues/160 now, which is basically the same as the ones I just created?

Just noting that I have a feeling we'd have to made adjustments to framework in order to make this achievable out of the box, because I don't think it's extensible enough yet - this is a hunch though, not a fact.

**Comment by ScopeyNZ** [comment]
> * The way we've architected the MFA module is that it has a `MemberAuthenticator` which replaces the core `MemberAuthenticator`.
> * In MFA's case I'm not convinced that is necessary, since it doesn't really care what happens with the email and password - it's only concerned with adjusting the authentication flow _after that happens_.

There's one important clarification here. We do actually come in just before the end. The email/password is verified but we jump in the authentication flow just before the log in actually occurs.
 
----

I think we should just add the code you mentioned in your SS4 docs (about LDAP) into the LDAP module. We can put some of that `class_exists` hacky-ness in and we can do some "if module exists" config to auto-wire it.

**Comment by ScopeyNZ** [comment]
I've merged the two docs PRs. This is good discussion, but the issue has been addressed so I'll close this. Discussion can continue on the two new issues raised (see OP).
