### ISSUE TITLE
Should 'add another method' auto-select a method?

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#174]
### Description
When adding a new MFA method using the CMS settings, it seems the modal will default to the registration screen of a method. I'm raising this issue to discuss whether this is expected and desired behaviour.

### Questions
- If there are more than one available additional method, what happens?
- If there are more than one available additional method, but one is unavailable due to browser restrictions, what happens?
- Are there accessibility concerns with defaulting to a method? I.e does the user know what method is being registered before they're presented with the registration modal?

**Comment by brynwhyman** [comment]
May have been purposefully implemented this way with #93

**Comment by ScopeyNZ** [comment]
Yeah that's on purpose. But this is a use case where it shouldn't be like this. From memory the designs actually had a design showing all the methods available on that screen regardless of whether they were registered or not, but had a state for registered methods. This isn't implemented - and I'm not sure if we have an issue to do that - but this sort of UI enhancement would be impact/low imo.

**Comment by brynwhyman** [comment]
@ScopeyNZ I've taken the action from your comment to a new issue: #181 

Closing this issue with the answer to the title being: "Ideally, no. Future enhancements are captured in #181".
