### ISSUE TITLE
Cannot register first method from CMS

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#175]
### Description
If a user does not have a registered method, and attempts to add an MFA method through `/admin/myprofile` they are unable to.

### Steps to recreate
1. Have a user that has previously skipped registration (so has no registered methods)
2. Visit `/admin/myprofile`
3. Attempt to add a method by selecting the button 'Add an MFA method'
4. Select 'Authenticator app' and 'next'
5. Identify the process fails, the modal closes, and the 'Add an MFA method' button disappears. 

At step 5, there's a console error: `Error: Injector.get(): Component TOTPRegister does not exist`

### Expected result
A user is able to add their first MFA methods through `/admin/myprofile`

### Notes
- This doesn't appear to happen for the WebAuthn method.
- Tested on certnzmfa2.demo.silverstripe.cc

**Comment by ScopeyNZ** [comment]
🤔 This was certainly working for me. Also the error is strange. Like TOTP client code hasn't been added properly.

**Comment by brynwhyman** [comment]
Thinking that a refresh of the page would workaround this bug?

**Comment by robbieaverill** [comment]
I've reproduced this:

* A user has security key registered
* They login and go to their profile
* They add a new method, choose basic math from the options (basic math and TOTP) and register it
* The component reloads (redux update)
* They try to add another method so they can add TOTP

Console error: TOTPRegister does not exist. You can refresh the page for it to work again.

**Comment by NightJar** [comment]
Horribe but valid solution:
Use `Requirements` in the MFA modal boot, which will automatically set headers on the `HTTPResponse` - jQuery.onDemand (existing CMS functionality) will do the rest.

**Comment by robbieaverill** [comment]
I’m not sure that works in SS4, which is why we usually apply requirements globally to LeftAndMain

**Comment by NightJar** [comment]
Pretty sure it's still a thing. Whether or not it could be leveraged from the modal load without being a race condition I'm not so sure about.

![image](https://user-images.githubusercontent.com/778003/59576237-26086000-9113-11e9-98c5-f2d930ed67de.png)

**Comment by robbieaverill** [comment]
It doesn't work in SS4, I've raised an issue to track it here: https://github.com/silverstripe/silverstripe-admin/issues/897 and will move the requirements to LeftAndMain so they're always available for now.

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-mfa/pull/195
