### ISSUE TITLE
If only method is unavailable, still allow the back button

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#176]
Separating from #93 :

If only one method is installed (WebAuthn) but its unaccessible due to the site being accessed over HTTP or through an unsupported browser, we need to make sure that the 'Back' button is still available for the user to return to the previous screen.

From there, they user could use the skip function (if available).

See:
![image](https://user-images.githubusercontent.com/15868440/59174849-35cdf480-8ba7-11e9-8dfa-f4b40ac8322b.png)

**Comment by ScopeyNZ** [comment]
There is possibility here that you can get stuck. If MFA is mandatory and the only option is Webauthn then what do you do.

**Comment by brynwhyman** [comment]
Trying to capture that scenario separately in #93

**Comment by robbieaverill** [comment]
Yeah it works fine. I fixed another issue with this process here: https://github.com/silverstripe/silverstripe-mfa/pull/209, but this issue can be closed.
