### ISSUE TITLE
[Demo review] User MFA management, reset/remove not working

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-mfa#177]
![User MFA settings](https://user-images.githubusercontent.com/8085295/59228406-d36b0780-8c2b-11e9-9eb1-16308e6462eb.png)

Some of these might simply be functionality thats yet to be merged in, but I thought I'd just put it in just in case

**Comment by brynwhyman** [comment]
Covered in #171.

Re the date format. That's managed in the CMS by updating the 'Language Interface' in `admin/myprofile`. I updated it to English (United Kingdom) and it changed the format - so that one's fine.
