### ISSUE TITLE
Separate MFA configuration for frontend/backend users

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#179]
### Overview
It's plausible that a site may have different security requirements for backend (CMS) and frontend users - where MFA may be required for the CMS but optional for frontend users.

### User story
As a developer, I want the ability to enable distinct MFA settings based on user permissions, so that MFA could be enforced for one set of users and optional for another set.

### ACs
- There is configuration at a developer level to separately manage how MFA is enforced for at least two types of member permissions.

**Comment by robbieaverill** [comment]
@brynwhyman given that MFA is enabled only for CMS access users (configurable) does this ticket need to remain open?

I'm unsure what the actions for it.

**Comment by brynwhyman** [comment]
This issue covers functionality requirements that are far from the scope of our current implementation project. Closing.
