### ISSUE TITLE
Show existing methods when registering another

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#181]
Raised as a follow up action from #174 

### Overview
If a user has at least one method and wants to register an additional method, they can do so through the 'Add another method' in `admin/myprofile`.

Currently, if there is only one unregistered method available, selecting 'Add another method' will default to the registration screen of that method. This could be improved to first give the user a better idea of what's already registered and what their options are.

### User story
As a CMS user registering a new method, I want to see what methods I already have registered before selecting a new one, so that I have a clear idea of what methods are still available for me to use.

### Notes
- I'm unsure on what the current functionality will be if there are two unregistered methods available. Will it only show these two, or also the one that is already registered?

**Comment by newleeland** [comment]
Potential design
https://invis.io/H2R2N2EFTMY#/321186220_CMS_-_Login_-_2FA_-_Editing_-_Reseting_-_User_Settings
Press **Add another method**

**Comment by robbieaverill** [comment]
>As a CMS user registering a new method, I want to see what methods I already have registered before selecting a new one, so that I have a clear idea of what methods are still available for me to use.

To be fair, you have a list of your current methods already when you click the "add method" button.

I'm not sure I agree with this story TBH

**Comment by brynwhyman** [comment]
I see this issue as pretty low impact but I'm keeping it open while the project is ongoing. The designs are an improvement on what's there now.

The user story was purposefully written in a way so that it can be seen current functionality already meets the requirement.

**Comment by robbieaverill** [comment]
I'm still going to vote not to do this. My reasoning is that it's already obvious to the user what they have installed when they click the button that triggers this screen to be shown, and that introducing methods that are already registered into the UI means we have two ways that this screen can be rendered (CMS: with existing methods, frontend: without) which adds complexity to the code.

**Comment by brynwhyman** [comment]
Closing this. Any perceived benefit isn't going to be worth the additional work, given what current functionality is already in place.
