### ISSUE TITLE
Change "More options" button text to "Try another option"

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-mfa#182]
On the verify screens. Needs confirmation if this applies to registrations as well.

cc @silverstripeux

**Comment by newleeland** [comment]
What did you mean by "registrations"? did you mean like when setting up account and registering the methods? There are no points in MFA setup flow where the user would need a "try another option" button. This only applies in the login flows.

**Comment by robbieaverill** [comment]
@newleeland all good. They're exactly the same thing in principle, but we can keep different text between them if you'd like.

**Comment by robbieaverill** [comment]
cc @sachajudd, still relevant?

**Comment by sachajudd** [comment]
Yeah happy to close.
