### ISSUE TITLE
Review email notification wording

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#185]
The email wording hasn't been reviewed outside of the development team.

Raising this to review the wording. See templates here: https://github.com/silverstripe/silverstripe-mfa/tree/master/templates/SilverStripe/MFA/Email

**Comment by brynwhyman** [comment]
cc @silverstripeux

**Comment by newleeland** [comment]
If you didn't request a password reset, feel free to delete this email and carry on

**Comment by sachajudd** [comment]
Some other suggestions: "If you did not request a reset, you can ignore this message", "If you didn’t make this request, please ignore this email.", or "If you didn't request a reset password, you can safely delete this email." I'm not sure about including "and carry on with your day." in the email 🤔

**Comment by brynwhyman** [comment]
I like the look of: "If you didn’t make this request, please ignore this email." because it could be added to the standard password reset email template - which is also missing a similar sentence.

Although, I'd say "did not" would be more clear than "didn't"

**Comment by brynwhyman** [comment]
I've raised the request separately, here: https://github.com/silverstripe/silverstripe-mfa/issues/214

Still happy for that issue to be updated if needed, but closing this issue. Thanks for reviewing this!
