### ISSUE TITLE
Create correct branches for each repo

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-mfa#201]
Each repository:

* mfa
* webauthn
* totp
* login-forms
* security-extensions

... will need a SS3 and a SS4 branch, which we'll call `3.0` and `4.0` rather than 1 and 2 etc.

We need to create these branches in preparation for the SS3 backporting.

**Comment by brynwhyman** [comment]
It seems like it would be good to do this so we can also look at tagging a Beta version of each module

**Comment by robbieaverill** [comment]
@silverstripe/creative-commoners perhaps we could have a `3` branch and use `master` as the SS4 branch? When we stabilise we'd end up with `3.0` branch, remove the `3` branch entirely, and continue with regular 4.x based branches as we do with other modules
