### ISSUE TITLE
Cannot add and remove a method from member profile in one go

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-mfa#203]
I think this is a stale CSRF token:

* Go to your profile in the admin area
* Add a new method
* Confirm and close the dialog
* Remove the method again

The request returns a 400 saying it timed out, which is a CSRF token failure message.

We get the CSRF token from `Config.get()`, which does come from the Redux store, but perhaps the token updates after the request and isn't updated in the store... needs investigation.

**Workaround:** refresh the page

**Comment by brynwhyman** [comment]
Watch out to test other MFA actions too. This bug as been previously raised (and closed) so just worth checking: https://github.com/silverstripe/silverstripe-mfa/issues/172

**Comment by robbieaverill** [comment]
Steps to reproduce:

* Go to your profile in the admin area
* Set up TOTP and security key
* Set security key as default method
* Set TOTP as default method

The above parts work correctly, then:

* Try to reset the authenticator app

You get a 400 response and invalid session message.

The Redux store CSRF token and the value in the XHR request for it are the same, but the backend returns an invalid response, which indicates that the admin module has not updated the Redux store with the updated CSRF token value after an XJR request completes.

**Comment by robbieaverill** [comment]
Repeated calls to set the default method do not update the CSRF token, but as soon as you hit "Reset" it regenerates it. This could be a mistake on our end implementing CSRF protection.

**Comment by robbieaverill** [comment]
Yeah... `RegistrationHandlerTrait::createStartRegistrationResponse()`:

```php
        // Add a CSRF token
        $token = SecurityToken::inst();
        $token->reset();
        $data[$token->getName()] = $token->getValue();
```

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-mfa/pull/232
