### ISSUE TITLE
MFA is enabled when there are no methods installed

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-mfa#206]
I expect to be able to log in and not be prompted for MFA.
Instead I am prompted for MFA with no way to continue with registration.
I can go back and skip though, thankfully.

![image](https://user-images.githubusercontent.com/778003/59842770-4d795a00-93ab-11e9-8696-aee8dbcbc42a.png)

**Comment by robbieaverill** [comment]
Perhaps we need to add another false return to the shouldRedirectToMFA method for when no methods exist

**Comment by NightJar** [comment]
I'm sure it used to be a thing (i.e. this is a regression), but am not 100% sure.
I am sure we've discussed it and come to the conclusion that that should be the case (MFA acts as if it is not installed at all if there are no methods installed).

**Comment by robbieaverill** [comment]
The method has this logic already:

```php
        if ($member->RegisteredMFAMethods()->exists()) {
            return true;
        }
```

But nothing to check the number of methods in the system

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-mfa/pull/210
