### ISSUE TITLE
MFA user help

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#217]
### User story
As a CMS user, I want access to help documentation, so that I know how to use and administer the MFA functionality when installed on my site.

### ACs
- Writing conforms to the internal SilverStripe user help [writing guide](https://silverstripe.atlassian.net/wiki/spaces/CC/pages/738033936/User+Help+Docs+-+Writing+Guide).
- Images and screenshots conform to the internal SilverStripe [image guide](https://silverstripe.atlassian.net/wiki/spaces/CC/pages/738033936/User+Help+Docs+-+Writing+Guide).
- There is information on both using (registering and authenticating) and administering MFA functionality.

### Notes
- PUX started some work, here: https://docs.google.com/document/d/1fTWakZFuZ1q2zoFbTsxWCo-uhOwp2Q2VF4DqUS08VKs/edit#heading=h.ytmh5r6qnk4
- This issue is intended to cover all user help creation.
- Expect to write all docs in one repo (MFA)

**Comment by brynwhyman** [comment]
@silverstripeux said there might be a user help skeleton template

**Comment by brynwhyman** [comment]
PUX previously started this, so there's something to work off. Adding the Gdoc link in the notes section

**Comment by robbieaverill** [comment]
@brynwhyman @silverstripeux is this ready to go, in terms of us taking the Google doc and converting it into a user guide markdown file as of now?

**Comment by sachajudd** [comment]
I was looking to do a peer review over the docs next week and make sure it's ready to be converted over into markdown. That'll either be a job on your end or I can do it but it'd probably be towards the end of the month.

**Comment by robbieaverill** [comment]
Sweet, let us know when you think it's ready to be done
