### ISSUE TITLE
Update text for MFA

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-mfa#220]
### General text bugs:
7 text, 1 image improvement: http://app.toyboxsystems.com/magic/jayUqilq9MzO

**Security Key Graphic**
[U2F option.svg.zip](https://github.com/silverstripe/silverstripe-mfa/files/3323429/U2F.option.svg.zip)

**Comment by brynwhyman** [comment]
@newleeland can you please check the permissions on the Text Sizing link, I can't view it
