### ISSUE TITLE
Text sizing and padding

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#221]
##### Example
![photo_2019-06-25_10-04-06](https://user-images.githubusercontent.com/8085295/60055137-b73d8f00-9730-11e9-9869-f22ff0b512fd.jpg)
- [ ] Reduce H1 to 16px equivalent
- [ ] Reduce spacing between H1 and H2 to 8px equivalent
- [x] ~Increase paragraphs from 13px to 14px to improve legibility~
- [x] ~Increase subheading to 14px~

##### Example
![photo_2019-06-25_10-04-17](https://user-images.githubusercontent.com/8085295/60055142-ba387f80-9730-11e9-9de5-d4079de7d8e5.jpg)
- [ ] Add spacing between MFA options to 16px equivalent
- [ ] Add spacing to bottom of MFA graphic to 16px equivalent
- [ ] Add spacing after MFA options to 16px equivalent

**Comment by brynwhyman** [comment]
Paragraph sizing is coming from Admin CSS, so we won't alter those. Removed the checkboxes relating to that

**Comment by robbieaverill** [comment]
Noting that this issue is _not_ fixed by #231, I think that was a typo in the issue number

**Comment by Cheddam** [comment]
[PR here](https://github.com/silverstripe/silverstripe-mfa/pull/269).
