### ISSUE TITLE
Unable to print recovery codes

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#222]
When viewing recovery codes in the frontend MFA app (after registering a first method), selecting the 'Print codes' button does nothing.

**Console error:** `Uncaught TypeError: Cannot read property 'cloneNode' of undefined`

**Browser:** Chrome Version 75.0.3770.100 (Mac OSX)

**Notes**
- There's different issues for the CMS version of this, see #223

**Comment by robbieaverill** [comment]
Was this in the frontend or admin?

**Comment by brynwhyman** [comment]
Sorry, this was frontend. I've updated the description.

**Comment by robbieaverill** [comment]
Reproduced

**Comment by robbieaverill** [comment]
I'll do this as part of #223

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-mfa/pull/228

**Comment by indygriffiths** [comment]
Heads up this is still an issue on the 3 branch

```
bundle.js?m=1563836177:1 Uncaught TypeError: Cannot read property 'cloneNode' of undefined
    at e.print (bundle.js?m=1563836177:1)
    at t.value (bundle.js?m=1563836177:1)
    at Object.i (bundle.js?m=1563836177:1)
    at a (bundle.js?m=1563836177:1)
    at l (bundle.js?m=1563836177:1)
    at c (bundle.js?m=1563836177:1)
    at p (bundle.js?m=1563836177:1)
    at f (bundle.js?m=1563836177:1)
    at h (bundle.js?m=1563836177:1)
    at Ie (bundle.js?m=1563836177:1)
```

**Comment by robbieaverill** [comment]
We haven't backported the latest round of changes from the SS4 version yet - from memory #228 will be one of those changes
