### ISSUE TITLE
Recovery code actions redirect to frontend site

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#223]
When trying to use some recovery code actions (Print codes, or Copy codes), the user is redirected to the frontend of their site, and the actions aren't fulfilled.

Note, this only appears to happen with the CMS Admin modal.

**Steps to recreate**
1. Log into the CMS (with MFA as optional)
2. Register the first MFA method through the CMS modal
3. When first recovery codes are presented, attempt to: a. Print, or b. Copy codes.
4. Identify the bug that redirects the user to the frontend of the site.

**Expected results**
At step 4, the user is able to: print codes, copy codes, or both without being redirected away.

**Notes:**
Both buttons appear to link to: http://siteurl/#

**Comment by robbieaverill** [comment]
I don’t think we should be using anchors, we can use buttons instead - thoughts @cheddam?

**Comment by brynwhyman** [comment]
Note, you can also recreate this when viewing the modal on reset of existing recovery codes.

**Comment by Cheddam** [comment]
Rule of thumb for anchors vs. buttons:

- If it's a link, use an anchor.
- If it's a JS-based action, use a button. (Don't forget `type="button"`!)

**Comment by robbieaverill** [comment]
FYI can be reproduced by resetting existing backup codes as well

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-mfa/pull/228
