### ISSUE TITLE
Tag an RC for SS4 and SS3

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#225]
Mark the SS4 and SS3 branches as 'stable' by tagging a release candidate.

**Notes**
Creating this issue now to keep track of the dependancies involved in stable release.

- Sites with `silverstripe/subsites` installed will need to bump to the latest patch version of that module to use subsites. See: https://github.com/silverstripe/silverstripe-subsites/issues/431
  - We'll want to tag the MFA module as conflicting with previous Subsites versions, as it breaks login entirely
- ~Since we're likely to release this module as stable outside the CWP release cadence we'll want to release a new CWP patch version (for 2.3 only) to make use of refactored encryption. See https://github.com/silverstripe/cwp-core/issues/51~

**Comment by robbieaverill** [comment]
All tagged, SS3 and SS4
