### ISSUE TITLE
Cannot remove a method

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-mfa#234]
I am a user, with a single method registered; webauthn.
I am in the CMS, and I am editing my own profile.
MFA is optional on my site.
I click "Remove", and confirm the modal.
Nothing happens.

![image](https://user-images.githubusercontent.com/778003/60231569-cae22480-98ed-11e9-8e28-4950804709d5.png)

The error says "timed out", however I have only just loaded this page.

Does it mean "sudo mode"? If this is the case, there is no error state for that it seems.

**Comment by robbieaverill** [comment]
Fixed in https://github.com/silverstripe/silverstripe-mfa/issues/203
