### ISSUE TITLE
Limit data stored in MFA (Session)Store

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-mfa#236]
Currently we push all of the data submitted by the base login form into the (Session)Store during MFA processing, which _includes the raw password of the user_. There should be no need for us to keep this information around, and if the service backing the session (e.g. DynamoDB on a cloud platform) is compromised, we could unnecessarily leak it.

**ACs:**

- [x] Potentially sensitive information is no longer stored in the (Session)Store during MFA login / registration flows
- [x] Users can configure what information is stored in case they need to adjust this for their implementation

**Comment by robbieaverill** [comment]
I believe the password is in the store so you can delay the actual login process. We may be able to adjust MFA not to do this, but I'm not sure it'd be effort easy

**Comment by Cheddam** [comment]
True! We should be able to store something else, like "has-successfully-authed-with-password: true", once we've verified the password once.

**Comment by ScopeyNZ** [comment]
> True! We should be able to store something else, like "has-successfully-authed-with-password: true", once we've verified the password once.

I'm pretty sure this is how it works at the moment. I don't think we reference the password again in the MFA flow. 

The password is checked here: 

https://github.com/silverstripe/silverstripe-mfa/blob/master/src/Authenticator/LoginHandler.php#L85

`performLogin`/`doPerformLogin` shouldn't require the password.

**Comment by robbieaverill** [comment]
PR at #243

**Comment by NightJar** [comment]
Merged
