### ISSUE TITLE
Buttons to select an authenticator have a hover colour even when disabled

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-mfa#254]
This seems weird, but may be related to accessibility in some way.

As found during #247 when an authenticator is unable to be selected (the method tile, during registration), it still alters it's background colour on hover and focus. On focus seems somewhat logical (in that the element can be focussed even though it cannot be activated), however question has arisen around whether or not this should be the case, and most especially in regards to hover (for mouse users).

![image](https://user-images.githubusercontent.com/778003/60774072-a6464200-a162-11e9-8200-b8699eb44d6c.png)

(grey shows hover state, not "disabled")

compare to an active selected method (note blue border to show active):

![image](https://user-images.githubusercontent.com/778003/60774079-c2e27a00-a162-11e9-85eb-7cbd99ae9ed4.png)

@silverstripeux help please :)

**Comment by clarkepaul** [comment]
Yeah if we can remove the hover state completely for non-selectable items that would be good but in saying that the most important thing is the cursor change. The cursor change needs to show the cannot select pointer.

**Comment by robbieaverill** [comment]
[The designs](https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/322769156) don't seem to mention or indicate a hover state, so I'll remove it entirely.

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-mfa/pull/281

**Comment by ScopeyNZ** [comment]
Closed by #281.
