### ISSUE TITLE
[Demo bug] User cannot sign-in using MFA on IE11 & Edge

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-mfa#256]
When attempting to login into the CMS, the MFA verification screen did not fully load after the email address and password were submitted.

**Edge 16 & 17 (Win10)** (Edge 18 works)
<img width="1440" alt="Edge_16_17_Win10" src="https://user-images.githubusercontent.com/8085295/60860560-32439100-a26b-11e9-9943-563a9b9618b5.png">

**Edge 15 (Win10)**
Experience does not move beyond the loading indicator
<img width="1440" alt="Edge_15_Win10" src="https://user-images.githubusercontent.com/8085295/60860570-3ec7e980-a26b-11e9-9fad-432ca973f097.png">

**IE11  (Win7/8/10)**
<img width="1440" alt="IE11_Win10_8_7" src="https://user-images.githubusercontent.com/8085295/60860532-0de7b480-a26b-11e9-8d8a-b19b79238c43.png">

**Comment by robbieaverill** [comment]
We may need to polyfill some more modern JS calls we're using, judging by that last screenshot

**Comment by Cheddam** [comment]
A PR fixing support for IE 11 [has been merged](https://github.com/silverstripe/silverstripe-mfa/pull/278). A PR fixing support for Edge 14-17 [has been opened](https://github.com/silverstripe/silverstripe-mfa/pull/280).

**Comment by robbieaverill** [comment]
Nice work! Both PRs are merged into 4.0.x
