### ISSUE TITLE
Docs: Dont' support two of the same methods

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#258]
The [Setup](https://github.com/silverstripe/silverstripe-mfa#setup) section is out of date. A developer won't need to define the TOTP or Webauthn methods. 

- [x] This should be made clear that this is only relevant when getting a new authenticator module to be used with this module. I'd expect this is confusing developers who want to be using the beta version of this module.
- [x] Throw an exception if there is more than one method with the same URL segment and class name.

**Comment by robbieaverill** [comment]
PR at #285

**Comment by ScopeyNZ** [comment]
Closed by #285
