### ISSUE TITLE
Reject strings longer than expected

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#26]
From https://github.com/Firesphere/silverstripe-bootstrapmfa/issues/8

>No matter what, with U2F, OTP or TOTP, the string is supposed to be an expected length. Anything not matching the length should be rejected for security reasons.

>I believe this should be implemented as low level as possible. It can easily be done via a configuration setting of the module that bolts on top of the Bootstrapping.

**Comment by robbieaverill** [comment]
Perhaps we can interface this so people don't forget to implement it in their Methods. Something like `getExpectedLength()` (avoiding terms like "code" because they may not always be a code).

**Comment by brynwhyman** [comment]
It will either pass or fail validation. If you validate that it's supposed to be a certain length, this is probably going to be less secure. Going to close this issue.
