### ISSUE TITLE
Update translation strings

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-mfa#261]
The translation strings present in `lang/en.yml` still point to the pre-rewrite namespaces, and are out of sync with the translations we have in place now. 

**ACs**

- [x] Remove the lang/en.yml file entirely from the SS3 branch

**Comment by robbieaverill** [comment]
This just needs the text collector to be run, I'll do it now

**Comment by robbieaverill** [comment]
Alrighty, turns out it's a bit harder to do this than I thought. The text collector doesn't play very nicely with PHP 7, which is a requirement of MFA. I've updated the template translation syntax for SS3 in 3eeccc1 anyway.

**Comment by robbieaverill** [comment]
I've also updated MFA/TOTP/WebAuthn translations in the 4.0 branch and pushed them to Transifex

**Comment by robbieaverill** [comment]
We could actually just remove the lang/en.yml file entirely from the SS3 branch. People will need to write their own translation files anyway if they want non-English translations, and the defaults will be used from the `_t()` calls which are English

**Comment by robbieaverill** [comment]
PR At https://github.com/silverstripe/silverstripe-mfa/pull/282
