### ISSUE TITLE
Don't allow backup codes to be generated in certain circumstances

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-mfa#263]
Currently you can manually force backup code generation before you register a method during set up. We should assert that at least one other MFA method is created before backup codes can be generated

~Additionally, it probably shouldn't be possible to regenerate backup codes (if some already exist) without being fully logged in. The partial login state that you have when you first generate backup codes (while registering during login) should not allow you to __re__generate backup codes.~ - Turns out we did this 😅

**Comment by robbieaverill** [comment]
SS4 PR: #292
SS3 PR: #293
