### ISSUE TITLE
Add docs for max passwords attempts affecting mfa attempts

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-mfa#267]
We share the password attempts API for MFA attempts. We should document this.

Additionally we should probably add a test to ensure the password attempt is recorded.

**Comment by robbieaverill** [comment]
> Additionally we should probably add a test to ensure the password attempt is recorded.

Here's one we prepared earlier:

https://github.com/silverstripe/silverstripe-mfa/blob/0454110/tests/php/Authenticator/LoginHandlerTest.php#L485

**Comment by robbieaverill** [comment]
Docs PR at #284

**Comment by ScopeyNZ** [comment]
> Here's one we prepared earlier:
> 
> [/tests/php/Authenticator/LoginHandlerTest.php@`0454110`#L485](https://github.com/silverstripe/silverstripe-mfa/blob/0454110/tests/php/Authenticator/LoginHandlerTest.php#L485) [](/silverstripe/silverstripe-mfa/blob/HEAD@{2019-07-25T10:23:36Z}/tests/php/Authenticator/LoginHandlerTest.php#L485)

Damn. I went looking on my phone and I couldn't find it 😂

**Comment by ScopeyNZ** [comment]
Merged #284
