### ISSUE TITLE
Review (and fix) SS3 styling

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#268]
Thoughts on what may need fixing (but review yourself)

- The front end could do with a couple of tweaks to styes inherited from admin
- Sudo mode might need some attention

### MFA

- [x] https://github.com/silverstripe/silverstripe-mfa/pull/304
- [x] https://github.com/silverstripe/silverstripe-mfa/pull/303 

### WebAuthn

- [x] https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/52

### login-forms

- [x] Backport https://github.com/silverstripe/silverstripe-login-forms/pull/36
- [x] https://github.com/silverstripe/silverstripe-login-forms/pull/35

**Comment by newleeland** [comment]
Not super keen to do a full design review of the SS3 MFA, But I did notice some obvious visual bugs, like the need for padding on the main action buttons.

Would it be best to get to sit down together for 30mins and go over it, or use a local server?

**Comment by ScopeyNZ** [comment]
Hi @newleeland. I don't think we expected much (any) input from PUX here. Just make sure it doesn't look completely awful. There are some parts of the admin interface that inherited styling in SS4 that don't in SS3 and look a bit weird.

**Comment by brynwhyman** [comment]
I think a sit down with PUX is worthwhile before marking this issue as done. Around 60% of sites on our platform are running SS3. It would be good to ensure this version receives a similar level of design review before we mark this work as complete. 

cc @clarkepaul

**Comment by ScopeyNZ** [comment]
I think I've covered most bases now and it looks "good enough". PRs listed in the OP.

There's this issue: 

https://github.com/silverstripe/silverstripe-security-extensions/issues/15

Once that's fixed the invalid field styling might need a pass.

**Comment by ScopeyNZ** [comment]
Backported fixes from 4.0 so closing this
