### ISSUE TITLE
Timeout message presented in MFA app

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#273]
We've had a bug report come in.

### Report
(CWP site)
I’ve got an error message of “Your request timed out. Please refresh and try again” when I try and log in with the Google Authenticator on Chrome.

The TOTP code hasn’t timed out (it’s still blue not red), I’ve had this on two different days and had to use a back up code to get in.

![image.png](https://images.zenhubusercontent.com/5b17319354b51e4165e1fd0b/b56e0c25-1674-4435-8b64-025aea422e5e)

**Comment by ScopeyNZ** [comment]
Does refreshing and trying again not work? This should only happen if you leave the screen for an amount of time (which is 1440 seconds in CWP by default IIRC).

**Comment by robbieaverill** [comment]
Assuming refreshing and trying again works, I’d say close this as working as expected

**Comment by brynwhyman** [comment]
Yup, happy to close. There were reports of network slowness which may contributed to this.
