### ISSUE TITLE
MFA registration screen + skip registration

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#29]
### User story

As a CMS user without a registered MFA method, I want to be presented with a registration screen to set 
 up a MFA method up after I've logged in, so that I can add extra security to my CMS account.

Designs: https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/321189816

### ACs
- [ ] This is the first page of the React app, displayed after a successful CMS login
- [ ] This screen is only displayed to users without a registered MFA method
- [ ] If MFA is mandatory, and the grace period hasn't ended, this registration screen is shown each time a user logs in
- [ ] If MFA is non-mandatory, and the user has previously skipped registration, do not show this screen again
- [ ] Functionality exists to 'set up later' as per notes below
- [ ] Text in designs is static
- [ ] Create default styling within the app, using generic class names that could be overwritten by a site developer

### Skip functionality follows:
https://github.com/silverstripe/silverstripe-mfa/issues/14:
- [ ] Skip function is available if global grace period is enabled and it has not ended
- [ ] Skip function is available if MFA is not mandatory
- [ ] Skip function is hidden if MFA is mandatory and global grace period has ended

**Comment by brynwhyman** [comment]
>If MFA is non-mandatory, the registration screen will be shown intermittently to remind CMS users it is available

This might need further discussion. It would be good practise to remind users that MFA registration is enabled for them, but we may need to implement something to stop this screen from appearing permanently if the user doesn't want it.

**Comment by brynwhyman** [comment]
Graphics are exportable from the Invision flows

**Comment by brynwhyman** [comment]
In grooming we discussed how this would work for site users who have an account, but don't have access to the CMS. For these users, if they skip, they wouldn't have the ability to setup MFA later as they don't use the CMS. 

The MFA 'app' is permanlinked so the route could be built into the frontend by a developer, so it could be accessed again.

**Comment by Cheddam** [comment]
https://github.com/silverstripe/silverstripe-mfa/pull/63
