### ISSUE TITLE
[MFA Demo issue] Instance of image clipping modal title and action bar

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-mfa#295]
When adding or removing MFA settings within my CMS profile, image of TOTP clips the title bar on top and the actions bar below.

This issue was fixed on other views, however, remains for TOTP. Hey, @ScopeyNZ I think you did some work fixing the clipping on the other screens!

![Screen Shot 2019-07-30 at 2.18.38 PM.png](https://images.zenhubusercontent.com/596d365561b4ca3b0a74bd86/a8becf5b-6338-4b7b-b29d-5025d1228132)

## Pull requests

- [ ] https://github.com/silverstripe/silverstripe-totp-authenticator/pull/32

**Comment by ScopeyNZ** [comment]
Wasn't me. But there's also a rogue horizontal rule under the input too...

**Comment by NightJar** [comment]
@silverstripe/creative-commoners, can anyone tell me why fields on this interface use the CMS `form-group` class? This is the reason for the `margin-bottom: @thin-grey-line`

And the icon _always_ stick up over the header, c.f. front-end `login-forms`:
![image](https://user-images.githubusercontent.com/778003/62333536-f624e880-b517-11e9-96c6-7520a785a60d.png)

So I guess the question here is - how much do we want to make specific exceptions for the admin UI?

**Comment by NightJar** [comment]
I note that this behaviour is specific to `totp-authenticator`, where `webauthn-authenticator` uses CSS Grid:
![image](https://user-images.githubusercontent.com/778003/62333756-e3f77a00-b518-11e9-9fba-4c8172ac971e.png)

**Comment by robbieaverill** [comment]
Probably because the modules were written by different people, and there was an assumption that we can use Bootstrap (which we can) - feel free to refactor so it is consistent

**Comment by ScopeyNZ** [comment]
Seems like this issue probably belongs on TOTP. I think it makes sense to bring TOTP in line with Webauthn. I wonder what happens with the "choose method" screen 🤔 .

Also please use consistent `.mfa-action-list` classes on the actions (`webauthn` doesn't do this currently but `totp` does IIRC).

**Comment by NightJar** [comment]
Yes @robbieaverill we can use bootstrap, and I believe this component does. However it is the `silverstripe/admin` specific classes I'm querying the use of here. I guess the answer is "get rid of them". I was wondering if they were written in for a particular reason before I went ahead and bulldozed them out, only to find the roof collapsing in on me.

Selection screen is fine @ScopeyNZ as it uses exactly zero form elements - rather opting for `role="button"` for the option list
![image](https://user-images.githubusercontent.com/778003/62334047-2c636780-b51a-11e9-972e-3d3850076263.png)

Combing over all CSS for consistency does expand the scope of this issue a wee bit, but I'll give it a go.

**Comment by ScopeyNZ** [comment]
Sorry, I meant the select method screen during verification, not registration 😅 . I know that has a right aligned image too.

**Comment by NightJar** [comment]
Another winning application of CSS Grid :)

![image](https://user-images.githubusercontent.com/778003/62334506-0dfe6b80-b51c-11e9-9232-be9f874bc38d.png)

**Comment by NightJar** [comment]
PR: https://github.com/silverstripe/silverstripe-totp-authenticator/pull/32
I did not address classname consistencies.
