### ISSUE TITLE
[MFA Demo issue] adding fullstops and question marks

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-mfa#296]
##### Add fullstop to the end of description when resetting recovery codes:
![Screen Shot 2019-07-30 at 2.20.13 PM.png](https://images.zenhubusercontent.com/596d365561b4ca3b0a74bd86/f119a3c7-2895-46dc-8fc9-b48b58f0b1c6)

##### Add Question mark to the end description when removing methods:
![Screen Shot 2019-07-30 at 2.19.54 PM.png](https://images.zenhubusercontent.com/596d365561b4ca3b0a74bd86/0dd88882-4f7a-4b89-b34c-158b1d494071)

**Comment by ScopeyNZ** [comment]
Closed by #300
