### ISSUE TITLE
Feature pictograms are different widths on render

### ISSUE THREAD

**Issue by indygriffiths** [silverstripe/silverstripe-mfa#301]
Something weird going on with the layout of the pictograms when the screen is rendered, despite the width/height being set correctly in the CSS to 50px the icons are different widths.

![image](https://user-images.githubusercontent.com/32345766/62178857-9bb44c80-b39e-11e9-9334-52fc7dddfc5c.png)
![image](https://user-images.githubusercontent.com/32345766/62178902-c0102900-b39e-11e9-96d1-64dc45c568f1.png)
![image](https://user-images.githubusercontent.com/32345766/62178910-c8686400-b39e-11e9-8b85-72cb7692583b.png)

Removing and re-adding the `width: 50px ` on `.mfa-feature-list-item__icon` makes them the correct width.
![image](https://user-images.githubusercontent.com/32345766/62178950-e2a24200-b39e-11e9-8498-86011623c18d.png)

Could be custom code related but raising anyway just in case.

**Comment by ScopeyNZ** [comment]
@Cheddam might be able to shed some light (read; frustrations) on this?

**Comment by Cheddam** [comment]
My initial impression was that this is a browser bug in Chrome, as it fixes itself when you try to adjust the CSS via devtools (toggling the width property will immediately repaint it correctly). However, I've since noticed that this is a consistent issue in IE 11 - it doesn't go away there with modifications in the devtools.

Hopefully if we can identify a fix for IE, the inconsistent behaviour in Chrome will also be resolved.

**Comment by Cheddam** [comment]
Just noticed the _opposite_ behaviour in Safari (intermittently, as with Chrome):

![image](https://user-images.githubusercontent.com/242621/62438396-48c20700-b79b-11e9-8fad-48aa639aa96c.png)

I've experimented with making the second SVG inline, which resulted in Chrome rendering it at the incorrect size permanently. Something about these SVGs is confusing the dang heck out of browsers.

Further sleuthing required.

**Comment by indygriffiths** [comment]
Such a fun issue, noticed that if I right click on the link for that step the proportions change. 

![peekF9JS6Z](https://user-images.githubusercontent.com/32345766/63403368-19fe8e80-c433-11e9-842e-daca0e91e972.gif)

**Comment by robbieaverill** [comment]
Do we need a SS3 PR as well?

**Comment by NightJar** [comment]
Both SS4 and SS3 versioned merged :)
