### ISSUE TITLE
[MFA Demo issue] Update MFA setup titles to be more clear what the main action

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-mfa#305]
The titles of TOTP and Security Key MFA setup modals are not clear to content authors, who are new to the concept of MFA, of what they should be doing on those views.

Recommended text change:
Authenticator app >> Setup with an authenticator app
Security key >> Setup with a security key

<img width="645" alt="Screen Shot 2019-08-02 at 1 42 00 PM" src="https://user-images.githubusercontent.com/8085295/62338358-62a9e280-b52c-11e9-8aa5-1d2938f2b4bc.png">
<img width="635" alt="Screen Shot 2019-08-02 at 1 42 27 PM" src="https://user-images.githubusercontent.com/8085295/62338359-62a9e280-b52c-11e9-97bb-48bd1f9abdaa.png">

**Comment by robbieaverill** [comment]
@newleeland this will also change the registration UI, is that OK?

![image](https://user-images.githubusercontent.com/5170590/62339677-faa9cb00-b530-11e9-82cb-fee7675ce4e8.png)

**Comment by newleeland** [comment]
@robbieaverill yeah thats fine.

**Comment by NightJar** [comment]
The suggested change implied by also altering the MethodTile text means altering `method.name`, which would update e.g. "Verify with Authenticator App" to "Verify with Setup with an Authenticator App" - this is not ideal.

The string needs to be contextual (c.f. "Set up with **an** Authenticator App" vs "Set up with **a** Security Key"), and translatable (it is not as easy as checking to see if the `method.name` begins with a vowel).

The easiest way would be to pass the translation through from PHP via the Available Method Details Interface - but that would also in turn rely on either referencing a translation string not relevant to itself, but to the method - but not used on the method itself, OR introducing a new e.g. `getRegsiterWithText` method to the `MethodInterface` specifically for this. Neither of these seem ideal to me either.

Do we introduce a higher order component to inject this string via the related component and it's translation strings for the selected language at run time?

I'm not sure the best way forward here.

**Comment by ScopeyNZ** [comment]
Can't we just make the title `Setup with {method}` - and drop the "a/an". The verify side doesn't have the "a/an". Additionally, this can just be on the javascript side - we don't need to modify the name (similar to how verification does it).

**Comment by NightJar** [comment]
Seems like the best way forward, we can keep `Setup with {method.name}` as such more easily then too.
Does it get approval from @newleeland ?

**Comment by NightJar** [comment]
Although I will argue that it is "Set up with {method.name}" https://grammarist.com/spelling/set-up-vs-setup/

**Comment by NightJar** [comment]
@newleeland gave this the ✔️

**Comment by newleeland** [comment]
> Seems like the best way forward, we can keep `Setup with {method.name}` as such more easily then too.
> Does it get approval from @newleeland ?

Yeah thats a good idea.

**Comment by Cheddam** [comment]
Resolved by #317.
