### ISSUE TITLE
Method registration tiles: having three methods has extra padding on the third item

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-mfa#306]
![image](https://user-images.githubusercontent.com/5170590/62340235-faaaca80-b532-11e9-88d4-047c8248b26a.png)

There's a regression where the third MFA method tile has extra padding on its row. The tiles display fine when there's two per row.

**Comment by ScopeyNZ** [comment]
I feel like originally this third item did not stretch... Although we also used to show 3 in one row... You would only see one in a row on it's own when you had 5.

**Comment by robbieaverill** [comment]
True you're right - it was designed to do this:

* 1
* 1, 2
* 1, 2, 3
* 1, 2, then 3, 4 in two rows
* 1, 2, 3, then 4, 5 in two rows
* 1, 2, 3, then 4, 5, 6 in two rows

Anyway, it's a regression and a super low impact bug
