### ISSUE TITLE
[MFA Demo polish] add spacing to differentiate titles and paragraphs

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-mfa#308]
Add more spacing between title and paragraph would make it clearer to differentiate between title and content. i.e. 
From:
![Screen_Shot_2019-08-02_at_3_02_42_PM.png](https://images.zenhubusercontent.com/596d365561b4ca3b0a74bd86/d26e9ee0-c1cf-48d8-ac81-1aaf5534a404)
 
To:
![Screen_Shot_2019-08-02_at_3_41_52_PM.png](https://images.zenhubusercontent.com/596d365561b4ca3b0a74bd86/fc40f039-8a2c-4736-92e3-ea29b2731ecc)

## Pull requests

- [x] #343 
- [x] #344

**Comment by NightJar** [comment]
Hi @newleeland - are you able to confirm whether this is specific to the webauthn module, or to all methods?

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-mfa/pull/343
