### ISSUE TITLE
Member MFA report: remove number of registered methods filter

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#314]
We've recently implemented a member report to review details of MFA. There's a filter option to filter the results by 'no. of registered methods'.

This seems like an unlikely option to filter by, and it's expected to cause performance issues at scale. As a result, this issue is created to remove that filter.

ACs
- Filter is removed
- Report is tested at scale to confirm performance is still sufficient

**Comment by robbieaverill** [comment]
I've removed the filter in a WIP branch locally, which is fine, but as we suspected the report doesn't scale well at all - it reaches about 15 second generation time with only 2000 members. We'll need to adjust some of the logic to use a pure DataList instead of an ArrayList.

**Comment by robbieaverill** [comment]
PR at #316
