### ISSUE TITLE
Grace period input field is initially disabled when MFA is set to required

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-mfa#323]
**Affected: 3.0.0-rc1 and 4.0.0-rc1**

* Go to Settings
* Go to Access
* Set MFA to required
* Notice that the grace period input becomes usable (where previously disabled if MFA is optional)
* Save the page
* Notice that the grace period input becomes disabled (it should not be)

Workaround: toggle to optional then back to required again.

![image](https://user-images.githubusercontent.com/5170590/62841036-67725180-bcf7-11e9-8445-b044154da15d.png)

**Comment by Cheddam** [comment]
Resolved in #346 and #347.
