### ISSUE TITLE
Option to select authentication method

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#34]
As a CMS user registering a MFA method, I want to be able to chose which method to set up from available options, so that I can select my preferred method.

Designs: https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/321189815

ACs
- There is a selected state for verification methods
- The template has an area to display information on the authentication methods (including 'Find out more' link) which will be surfaced from the authentication method's own components
- The 'Next' button is disabled until a selection is made
- Styling is created, as per designs, to disable authentication methods that may not be available. This would be attainted from the method module. An example being U2F is only supported by default in Chrome v71+ so it would otherwise be disabled in another browser
- The user has the ability to go back to the previous screen
- Area has the ability to stack up to three 'method' boxes wide
- Create default styling within the app, using generic class names that could be overwritten by a site developer

**Comment by brynwhyman** [comment]
For the unsupported state, it sounds like the browser provides this information but only on https, so we'll need to consider what to do if the app is being viewed on http, e.g a local env

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-mfa/pull/62
