### ISSUE TITLE
Images are not resolved when installed on a subfolder

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-mfa#340]
**SS 3.x.** SS4 might be OK assuming we're using the module manifest loader to resolve file paths.

* Install a project in a subfolder
* Go to login
* See introduction MFA screen has broken images

![image](https://user-images.githubusercontent.com/5170590/63562072-5f949600-c5b0-11e9-9b0b-c42e4125ab54.png)

It's resolving to the root domain, not the project root.

![image](https://user-images.githubusercontent.com/5170590/63562127-89e65380-c5b0-11e9-9c72-6b894eea2c83.png)

My `BASE_URL` constant value is `ss37/`

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-mfa/pull/341
- [x] https://github.com/silverstripe/silverstripe-totp-authenticator/pull/42
- [x] https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/56

**Comment by NightJar** [comment]
This setup is how I work from home, I'm 95% sure there's no issue in SS4 :)
