### ISSUE TITLE
[SS3] AccountReset relies on SS4-only config option

### ISSUE THREAD

**Issue by indygriffiths** [silverstripe/silverstripe-mfa#351]
The AccountReset component references the `auto_login_token_lifetime` config option on Member when determining how long the reset token should last. This config field is only present in SS4, and because of this the SS3 version of this module is generating reset tokens that expire as soon as they're created.

https://github.com/silverstripe/silverstripe-mfa/blob/3.0/src/Extension/AccountReset/MemberExtension.php#L42

At the moment our workaround is to define this config value ourselves as SS3 doesn't do this in a ~sane~ sensible manner.
```
Member:
  auto_login_token_lifetime: 172800
```

**Comment by Cheddam** [comment]
This should be resolved as of 3.0.1.
