### ISSUE TITLE
Yubikey failure mode wording isn't clear

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-mfa#356]
If your security key has an error or times out, you get a screen that says "Please reinsert your key and activate it", with "Try again" and "More Options" buttons.

It's not clear (or at least it wasn't to me) that you have to click try again before re-inserting your key. Could we adjust the wording on that error screen slightly? I'm not sure what better wording might be, Paul or Jared might be able to help here?

**Comment by madmatt** [comment]
Yep that makes a lot of sense to me 👍

**Comment by robbieaverill** [comment]
It currently says "Something went wrong. Please re-insert your key and try again" which LGTM
