### ISSUE TITLE
Keys are re-useable across different users

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-mfa#357]
## As an admin
I would like to be able to prevent the same key to be used for multiple accounts

## So that
I can be sure any secrets are not shared across users

## Because
My CMS is not the size of Google/GitHub/etc. where it is common for users to have multiple accounts, compared to my website CMS.

**Comment by brynwhyman** [comment]
Thanks for the suggestion! What 'key' are you referring to here?

**Comment by Firesphere** [comment]
Specifically, physical keys (e.g. Yubikeys). A shared TOTP is practically impossible

**Comment by ScopeyNZ** [comment]
> I can be sure any secrets are not shared across users

Just FYI, most U2F keys generate private/key pairs for each registration, meaning that there's almost always a different public key per registration. Public keys should be different per registration (depends on device). Here's a good description here:

https://developers.yubico.com/U2F/Protocol_details/Key_generation.html

Also, I don't think that we should refer to a public key as a "secret". Disclosure of the registered key data does not give anybody elevated access as they still need the individual key. In fact, you can only use the original key to even check if registered key data applies to that key, so there's not really any information disclosure with registered key data.

I don't mind the idea of this as an enhancement - but I personally believe that it's really not any security improvement at all (right now) and should be treated as a very "impact/low" enhancement unless there's a good explanation for how this affects a users security at all.

**Comment by ScopeyNZ** [comment]
Issue moved to [silverstripe/silverstripe-webauthn-authenticator #61](https://github.com/silverstripe/silverstripe-webauthn-authenticator/issues/61) via [**ZenHub**](https://www.zenhub.com/)
