### ISSUE TITLE
Password update in CMS requires MFA

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#36]
As a CMS admin with MFA enabled on my site, I want all users registered with MFA to be required to authenticate with a second factor when updating their password in the CMS, so that all CMS user details are secure.

ACs
- Users with a registered MFA method will be required to authenticate with MFA when choosing to update their password in the CMS member settings.
- Flow is: 
   1. request to update password, 
   2. MFA authentication required, 
   3. on MFA success, forms to update password are presented
- Uses the CMS modal functionality

**Comment by brynwhyman** [comment]
@silverstripeux this is something that was written into the solution architecture document, but I don't believe there are designs for this yet. Can you please look at this?

**Comment by clarkepaul** [comment]
@brynwhyman Try the "Password reset flow" here https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/folder/components/5c68f96ffb26bb0018525d1a

**Comment by brynwhyman** [comment]
Hey @clarkepaul we have that flow captured with #27 but I've created this issue for users who are logged into the CMS already and want to change their password here:
![image.png](https://images.zenhubusercontent.com/5b17319354b51e4165e1fd0b/12b2b72d-c128-4f8c-9dc1-5b0f0c540296)

**Comment by brynwhyman** [comment]
Ah.. actually, I guess the flow isn't that different is it - the user could just get redirected to the MFA app to authenticate

**Comment by clarkepaul** [comment]
I think we might need to design the flow, we've missed the UI where the Password gets changed in the CMS. I think it would feel broken if you are taken outside of the CMS to verify a method so it'll need to be a modal problem is we'd need to include the whole experience of being able to select which method to verify the change. Maybe it was intended that the user still gets an email and then goes through the change flow outside of the CMS? needs a discussion.

**Comment by clarkepaul** [comment]
I think the flow might be as follows (suggestion):
- On a users own profile page in the CMS, they can click the "Change password" link
- You are presented with a modal to select your preferred way of verifying your identity
- You are then presented with the MFA authentication screen of your choice to verify your identity, which closes the modal if successfully validates
- You are then presented with the fields to edit your password (as per original UI without MFA)
- User needs to save the page as per normal

**Comment by brynwhyman** [comment]
I'd be keen to discussing how this could relate to the following RFC https://github.com/silverstripe/silverstripe-framework/issues/8595

The 'sudo mode' would appear to simplify the transition to handling the authentication of user for CMS actions (as the list is growing: site MFA settings, update password, update email, update/add MFA method, reset backup codes, etc)

**Comment by clarkepaul** [comment]
If we intend to intergrate the "[Sudo](https://github.com/silverstripe/silverstripe-framework/issues/8595)" modal here then the steps might differ slightly:

- On a users own profile page in the CMS, they can click the "Change password" link
- You are taken to a "sudo" login modal to:
  - Enter your current password
  - Select your preferred way of verifying your identity
  - You are then presented with the MFA authentication screen of your choice to verify your identity, which closes the modal if successfully validates
- You can make "Sudo" type edits within the CMS
- User needs to save the page as per normal

**Comment by ScopeyNZ** [comment]
> You are taken to a "sudo" login modal to:

With "accessway" - would you invision that the "sudo" login screen would be themed the same as the login page?

**Comment by clarkepaul** [comment]
Yup, makes sense I can't think of a reason why it wouldn't. Same form styles for sure, we might want to promote the SilverStripe brand slightly more than what I did in my original mock (that was more of a wireframe concept rather than a design).

**Comment by robbieaverill** [comment]
Triaged assuming sudo mode has been implemented

**Comment by brynwhyman** [comment]
Noting that we won't be relying on sudo mode for this work anymore.

**Comment by chillu** [comment]
This is what we said in 5.2 User Flows: General Experience Notes in the architecture doc:

> Credentials for MFA methods can be added, edited, or be removed, these changes will require verification using their password. Likewise if a password is updated, verification of the users MFA will be required to update the password.

From memory, this was provided by PUX according to the flows they've designed late last year. 

@brynwhyman said on the architecture doc:

> flagging that this is something we want to debate. With the implementation of sudo mode (hopefully this sprint) a user will be required to re-authenticate within an already valid session to make changes in 'Security'. To further require MFA to update their password seems like a barrier to what should be a simple task. We've been using GitHub as a reference to some of these flows and it's worth noting they don't require MFA for a password update.

I'll leave it up to PUX to figure out what's required here, but I'll note that there's three different ways to change our password:

 * "Forgot password:
 * `admin/myprofile`
 * `admin/security`

As long as those three are covered by by MFA verification, the statements made in the architecture doc are correct. That could be achieved through a generic "sudo" mode when entering those flows.

**Comment by brynwhyman** [comment]
I've updated the title of this issue to better summarise the user story. This issue only relates to updating a password within the CMS, through `admin/myprofile` and `admin/security`.

MFA is already required for users who have a registered MFA method and want to reset their password through the Forgot password flow, as implemented in #27.

>@brynwhyman said on the architecture doc:

To give more context in this issue, we're proposing to deviate from the previous requirements and not require MFA verification before updating a password within the CMS. It seems the main purpose of re-authenticating before updating a password is to mitigate CSRF and session hijacking, both of which could be mitigated by requiring the user to provide their 'current password' (within an existing session) before a new password could be created
Reviewing other services, it doesn't seem like a common flow to request multi-factor authentication multiple times within a session (which this issue describes implementing).

Given that 'Sudo Mode' is being mentioned here, the current state of play with that is somewhat captured [here](https://github.com/silverstripe/silverstripe-framework/issues/8595#issuecomment-497202489). Enabling a 'Sudo Mode' permission will only require the user's password to be re-entered.

**Comment by robbieaverill** [comment]
@brynwhyman update on sudo mode is that it's enabled inline for the MFA component, e.g.:

![image](https://user-images.githubusercontent.com/5170590/59081149-bfc85400-8940-11e9-83db-0a1ad57affba.png)

We built sudo mode as a React HOC for the MFA implementation, so it won't be able to be applied to the "change your password" fields yet. I've been chipping away at https://github.com/silverstripe/silverstripe-admin/issues/885 which will convert these fields into a React driven component, and could then have sudo mode applied to it, but until that happens how would you like to handle this issue?

**Comment by brynwhyman** [comment]
We've had internal agreement on my comment above and our internal architecture document has been updated to reflect this. I'm closing this issue as it's no longer a requirement of our implementation.

We could look at applying sudo mode to scenarios like this in the future, but given that sudo mode only requires a password, there's not going to be a reduction in security until then.
