### ISSUE TITLE
Load translation in Backend

### ISSUE THREAD

**Issue by BW-Hosting** [silverstripe/silverstripe-mfa#364]
Error on load en.js in backend:
GET https://www.website.de/resources/vendor/silverstripe/mfa/client/lang/en.js?m=123456789 net::ERR_ABORTED 404 (Not Found)

Solution:
Change composer.json from:
`"extra": {
        "expose": [
            "client/dist"
        ]
    },`

to

`"extra": {
        "expose": [
            "client/dist",
            "client/lang"
        ]
    },`

**Comment by ScopeyNZ** [comment]
Ah yes that's a mistake. Would you like to make a PR?

**Comment by ScopeyNZ** [comment]
Closed in #368
