### ISSUE TITLE
New CMS users can define own password

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#37]
As a site owner, I want to provide the ability for users to set their own passwords, so that CMS admins are not defining passwords for users.

ACs 
- The CMS admin can still create new members 
- The CMS user has the ability to create their password before their first login
- The solution decision takes into consideration sites that do not have email capability
- The solution decision takes into consideration how this will work for UAT environments

Notes:
- Expect this would be implemented at a framework level. We may need to think about the release process for this if MFA will be released in July.
- So far there's been designs for two POCs:

***Option 1 - note we won't be proceeding with this option***
Create an 'invite' email:
- At `/admin/security/EditForm/field/Members/item/new` the password field are removed
- The 'Create' action is replaced with a 'Save and invite' action
- On 'Save and invite' an invitation email is sent to the new user
- An alert is presented in the CMS to notify the CMS admin that an email has been sent
- The email provides an invitation link to complete the set up of a user, prompts to create a password in a login form
- *Designs*: https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/325486638
- To support this flow there are issues written to handle 'pending' users, and reports to identify them. See #38 and #39

***Option 2***
Checkbox to require password reset:
- Admin is still able to create passwords for CMS users
- Can select checkbox to require a password reset on next login
- Admin can make a decision to not require the reset if on UAT, etc
- *Designs*: https://invis.io/S4R70OO3EYH#/354256399_CMS_-_Setup_-_Account_Creation_-_Admin_Set_Password_Copy

**Comment by brynwhyman** [comment]
>On 'Save and invite' an invitation email is sent to the new user
Email template TBC

>At /admin/security/EditForm/field/Members/item/new the password field are removed
Another option would be to keep these fields and have an additional 'Require new password on login' check box that if selected, makes any entered password valid for one time only.

**Comment by newleeland** [comment]
After talking with @clarkepaul, it was mentioned that the above flow was not what you had expected @brynwhyman. Was a design like this what you were expecting Bryn?
https://invis.io/S4R70OO3EYH#/354256399_CMS_-_Setup_-_Account_Creation_-_Admin_Set_Password_Copy

There are couple of consideration for using this flow
- user needs additional buttons links to cancel and resend invites
- its not obvious to user that an invite email will be sent by clicking **Create** button

**Comment by brynwhyman** [comment]
I see you've updated the link (https://invis.io/S4R70OO3EYH#/354256399_CMS_-_Setup_-_Account_Creation_-_Admin_Set_Password_Copy) this is what I'll reference with the below.

The intention here is a minimal flow that does not present an option to send an email from the CMS. The admin can simply:
- edit a CMS users password; and
- select the option to require a password reset on the next login

**Comment by clarkepaul** [comment]
The description for option 1 is no longer aligned to design anymore so the text will need some updating if we go with that approach.

**Comment by newleeland** [comment]
Please bare in mind these are not final designs. would be good to sit down with someone to nut out a direction and lock down a solution

**Comment by brynwhyman** [comment]
Would this make sense to be built in a separate module, or included in potential sudo mode module, to help with eventually moving this to framework?

**Comment by robbieaverill** [comment]
It's pretty mutually exclusive to sudo mode, so I'd advise against putting it there. I'd suggest that we could build this directly into MFA for now and if we have time we can also make a PR into framework.

**Comment by NightJar** [comment]
`Option 1`
>we won't be proceeding with this option

`Option 2`
#154
