### ISSUE TITLE
Lack of "client/lang" in composer.json

### ISSUE THREAD

**Issue by alessandromarotta** [silverstripe/silverstripe-mfa#372]
Hello to everybody.
I found out the lack of "client/lang" in composer.json to prevent the error 404 for the file "_resources/vendor/silverstripe/mfa/client/lang/en.js" 

**SOLUTION**:
- add "client/lang" in composer.json, "expose" section, like here:

"extra": {
        "expose": [
            "client/lang",
            "client/dist"
        ]
}

Bye,
Alessandro

**Comment by robbieaverill** [comment]
Good point, would you like to make a PR to fix this @alessandromarotta?

**Comment by brynwhyman** [comment]
Hi @alessandromarotta, if you're still interested in submitting a pull request to resolve this issue we'd love your help!

**Comment by michalkleiner** [comment]
@brynwhyman this was fixed via #368, not sure why it's not in 4.0.3 that was released since then.

**Comment by michalkleiner** [comment]
@brynwhyman ok, the issue is that `4.0.3` was tagged on `4.0` branch whereas the fix and other stuff were merged to `4` branch.
So the workflow there needs fixing (or merging `4` to `4.0` or the other way round, can't tell what is the preferred way, and then publishing a new version `4.0.4`.

**Comment by robbieaverill** [comment]
Fixed in 4.0.4, thanks @michalkleiner

**Comment by brynwhyman** [comment]
Thanks for looking a little deeper @michalkleiner!
