### ISSUE TITLE
(CMS3) Users with no CMS access can't authenticate when MFA is mandatory

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-mfa#376]
#### Affects

~MFA 4.0.x~, 3.0.x

#### Description

Following on from #369, we've received and corroborated a report that Members with no CMS access are barred from completing login when MFA is configured to be mandatory. This is due to a discrepancy in behaviour between the methods used to determine whether a user can bypass MFA at different stages of the login process:

- When determining whether to prompt for MFA, [`EnforcementManager::shouldRedirectToMFA()`](https://github.com/silverstripe/silverstripe-mfa/blob/fb7849fb752a229a4b2968c04b88651c6fccfe89/src/Service/EnforcementManager.php#L95) is called, which determines whether the user has access to the CMS and returns `false`, allowing login to proceed.
- Later, after login has completed, [`MFA\MemberAuthenticator\LoginHandler::redirectAfterSuccessfulLogin()`](https://github.com/silverstripe/silverstripe-mfa/blob/fb7849fb752a229a4b2968c04b88651c6fccfe89/src/Authenticator/LoginHandler.php#L432) calls [`EnforcementManager::canSkipMFA()`](https://github.com/silverstripe/silverstripe-mfa/blob/fb7849fb752a229a4b2968c04b88651c6fccfe89/src/Service/EnforcementManager.php#L63), which _does not_ check whether the user has access to the CMS and therefore returns `false`, causing an immediate logout and redirect to the authentication screen.

#### Replication

- Create test Member with no CMS permissions
- Set MFA to be mandatory in Settings
- Attempt to log in as test Member, observe immediate redirect back to login

#### PRs

- [x] 4.0 branch: #379 
- [x] 3.0 branch: #382

**Comment by robbieaverill** [comment]
🤦‍♂

**Comment by Leapfrognz** [comment]
I can confirm that users who do not have access to ALL CMS sections (CMS_ACCESS_LeftAndMain) will not get passed to MFA authentication. Im not sure if this is the same issue, or a symptom of the same settings.
I do believe this should be checking CMS_ACCESS rather than CMS_ACCESS_LeftAndMain
SS3, CWP 1.9.3

**Comment by Leapfrognz** [comment]
Also, technically, setting
```
LeftAndMain:
    required_permission_codes: false
```
Shoud disable this, but ` $this->stat('required_permission_codes');` is used, and not `Config::inst()` so it wont work

**Comment by Cheddam** [comment]
@Leapfrognz A fix for that particular case (reported in #369) has been developed and released for the CMS 4 branch of MFA, but not yet backported to the CMS 3 version (I've put some time into it, but it makes use of an API that isn't available in CMS 3 so it's taking longer than I'd hoped.) Watch this space!

**Comment by Cheddam** [comment]
Resolved as of 4.0.5 and 3.0.1.
