### ISSUE TITLE
Test and merge CMS 3-related pull requests

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#396]
https://github.com/silverstripe/silverstripe-mfa/pull/382

**Comment by dhensby** [comment]
Hey, I'm going to close this. It's pretty hard for core maintainers (that aren't full time employed to work on the project) to keep on top of everything when tickets are opened which essentially say "look at this PR" - the existence of a PR means it needs to be dealt with.

I recommend assigning the PR to someone if there's a need for someone specific to action it.
