### ISSUE TITLE
Attribution is missing

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-mfa#404]
The readme is missing attribution to my original work.

**Comment by michalkleiner** [comment]
Fancy raising a pull request?

**Comment by dhensby** [comment]
The [Licence](https://github.com/silverstripe/silverstripe-mfa/blob/4/LICENSE.md) still references you, @Firesphere 

If there's some specific wording you'd like used in the README, I think that you should raise a PR to have it added. Thanks!

**Comment by Firesphere** [comment]
@michalkleiner @dhensby 

When the team decided to go a different way than my intended use, it was agreed upon, that there would be a section outlining that the original base code came from my work, and there would be a section outlining the differences in approach etc.

This seems to not have been done, as well as the original mark that this was a fork has changed.

Because of the original agreement, I do not feel I should be the one making a PR for that.

@brynwhyman

**Comment by michalkleiner** [comment]
Gotta love the issue number :-D

<img width="409" alt="404" src="https://user-images.githubusercontent.com/233342/93015103-c8f7a480-f60a-11ea-9933-0bc8d014e877.png">

**Comment by Firesphere** [comment]
@emteknetnz This does not "affects/v4", this affects _any_ version.
If it's only applicable to SSLTD 4, then I believe the labels should be more verbose?

Otherwise, cheers for the labeling!

**Comment by brynwhyman** [comment]
Hey @Firesphere, you're right! We did discuss early on that in an effort to follow 'good forking edict' an explanation could be added to the readme explaining: the reason to fork from another module and if there was no plan to merge the fork back in the origin, how the implementations differ.

We'll get something up for a PR. Also, 

> Gotta love the issue number :-D

That is a little funny :P

**Comment by Cheddam** [comment]
Hey @Firesphere, I've raised a PR at #406 - let me know what you think. Sorry about the lack of visible attribution, and thanks for all of your work and support!

**Comment by dnsl48** [comment]
Merged. Virtual hugs to you Simon!

![unicorn](https://user-images.githubusercontent.com/9313746/93169119-86ec7100-f778-11ea-93e0-030270a77083.gif)
