### ISSUE TITLE
Missing records for frontend translations

### ISSUE THREAD

**Issue by SanderHamaka** [silverstripe/silverstripe-mfa#412]
I tried to translate this module to Dutch. After fixing the translations in nl.js and nl.yml some strings were still in English. It looks like these are used in the frontend code (bundle.js) but are not present in en.js or en.yml:

     "MFARegister.REGISTER_WITH": "Register with {method}",
      "MFARegister.NEXT": "Register with {method}",
      "MFARegister.BACK": "Register with {method}",
      "MFARegister.RECOVERY_HELP": "Learn more about recovery codes.",
      "MFARegister.TITLE": "Multi-factor authentication",
      "MFARegister.SETUP_COMPLETE_DESCRIPTION": "You will be able to edit these settings later from your profile area.",
      "MFARegister.SETUP_COMPLETE_CONTINUE": "Continue",
      "MFARegister.HELP": "Find out more.",
      "MFABackupCodesRegister.DESCRIPTION": "Recovery codes enable you to log into your account in the event your primary authentication is not available. Each code can only be used once. Store these codes somewhere safe, as they will not be viewable after leaving this page.",
      "MFABackupCodesRegister.PRINT": "Print codes",
      "MFABackupCodesRegister.DOWNLOAD": "Download",
      "MFABackupCodesRegister.COPY": "Copy codes",
      "MFABackupCodesRegister.FINISH": "Finish",
      "MFABackupCodesVerify.NEXT": "Next",
      "MFABackupCodesVerify.DESCRIPTION": "Use one of the recovery codes you received",
      "MFABackupCodesVerify.LABEL": "Enter recovery code",
      "MFAMethodTile.UNAVAILABLE": "Unsupported: ",
      "MFAVerify.MORE_OPTIONS": "More options",
      "MFAVerify.METHOD_UNAVAILABLE": "This authentication method is unavailable",
      "MFAVerify.VERIFY_WITH": "Verify with {method}",
      "MFAVerify.TITLE": "Log in",
      "MFAVerify.BACK": "Back",
      "MFAVerify.LAST_RESORT_MESSAGE": "Contact your site administrator if you require your multi-factor authentication to be reset.",
      "MFASelectMethod.UNAVAILABLE": "unavailable",
      "MFAVerify.OTHER_METHODS_TITLE": "Try another way to verify",
      "MultiFactorAuthentication.MORE_OPTIONS_IMAGE_ALT": "Graphic depicting various MFA options",
      "MFALogin.SOMETHING_WENT_WRONG": "Something went wrong!",
      "MFALogin.TRY_AGAIN": "Try again"

**Comment by emteknetnz** [comment]
These are defined in the src js files using the `_t()` function which includes a parameter for a default strings

e.g.
https://github.com/silverstripe/silverstripe-mfa/blob/4/client/src/components/Register/MethodTile.js#L113

Regards
Steve

**Comment by SanderHamaka** [comment]
Hi Steve,

They are indeed defined in source. But I think it would be nice to include these defaults in en.js or en.yml as well along with the ones that are already there. The current situation, in my opinion, discourages usage of this module on non English locales because developers have to search the source to collect all the default texts. This is very time consuming and error prone. Besides that, the presence of the lang and client/lang folders suggests that translating those texts is what has to be done to translate this module. Doing so results in a partially English experience.

For instance compare SETUP_COMPLETE_DESCRIPTION on:

https://github.com/silverstripe/silverstripe-mfa/blob/4.2/client/src/components/Register/Complete.js

and

https://www.transifex.com/silverstripe/silverstripe-mfa/viewstrings/#en/master-js?q=key%3ASETUP_COMPLETE_DESCRIPTION

Regards,
Sander
