### ISSUE TITLE
Not showing MFA settings

### ISSUE THREAD

**Issue by NayanaMadhuwantha** [silverstripe/silverstripe-mfa#423]
Hi,

I'm using SilverStripe 4.1.2
The MFA settings are not showing. Installed several versions of MFA but not fixed.

![image](https://user-images.githubusercontent.com/28913797/108980816-1a27bc00-76b2-11eb-9b5c-e8d578c1a50c.png)

**Comment by ScopeyNZ** [comment]
Is there an error in the browser console?

**Comment by NayanaMadhuwantha** [comment]
> Is there an error in the browser console?

No, not showing any errors

**Comment by NayanaMadhuwantha** [comment]
> Is there an error in the browser console?

Yes, There are some errors and warnings.

![image](https://user-images.githubusercontent.com/28913797/109110722-ab07a180-775d-11eb-86a4-bf60962f6cc0.png)
--
![image](https://user-images.githubusercontent.com/28913797/109110773-c1156200-775d-11eb-9466-310640593c91.png)

**Comment by ScopeyNZ** [comment]
Thanks 🙂

**Comment by brynwhyman** [comment]
Hi @NayanaMadhuwantha , did you manage to get this working? My first guess would be that CMS 4.1 is too early of a version to properly support the MFA module. I'd recommend trying with a later (supported) version of Silverstripe CMS if possible. I'll close this for now but can reopen as required.
