### ISSUE TITLE
MFA in the CMS (create the modal)

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#46]
Create the ability to show the MFA app in the CMS. This would be rendered in a modal.

Example design, that would be handled in separate issues: https://projects.invisionapp.com/share/H2R2N2EFTMY#/screens/352910417

ACs
- The modal should be stand alone
- Able to initialise the app in different views, i.e display recovery codes when reset in the CMS.

**Comment by brynwhyman** [comment]
I'd be keen to discussing how this could relate to the following RFC https://github.com/silverstripe/silverstripe-framework/issues/8595

The 'sudo mode' would appear to simplify the transition to handling the authentication of user for CMS actions (as the list is growing: site MFA settings, update password, update email, update/add MFA method, reset backup codes, etc)

**Comment by brynwhyman** [comment]
> I'd be keen to discussing how this could relate to the following RFC 

I think this is less relevant now as we've been investigating only requiring a password to enter a potential sudo-mode, not full MFA authentication.

**Comment by ScopeyNZ** [comment]
> whether the implementation of 'Accessway' makes this issue redundant

I thought that adding additional MFA methods would still use a modal and not the "accessway"/login flow - I'm very happy to be told otherwise.

/cc @silverstripeux

**Comment by clarkepaul** [comment]
I also thought it was still in the modal too. I see Accessway is an authenticating tool (provides initial signup for just one method and then after that, it only serves a purpose of authenticating? the others need to be added via the CMS). I think the user flow isn't going to be the best if every time you need to add to your settings you get taken away.

**Comment by brynwhyman** [comment]
I'm open to using the modal, my comment was just meant to ask the question of an alternative.
