### ISSUE TITLE
Update translation for MFA

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-mfa#469]
A partner has spent a fair bit of time preparing Finnish translation for this module. We should tag a patch release with updated translations so they can enjoy the fruits of their labour.

## Acceptance criteria
- [ ] MFA translation are pull down.
- [ ] A patch release is tag.

## PRs
- https://github.com/silverstripe/silverstripe-mfa/pull/470
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/101

**Comment by NightJar** [comment]
[Ref](https://github.com/silverstripe/silverstripe-mfa/issues/441)

**Comment by GuySartorelli** [comment]
PRs merged and releases tagged.
