### ISSUE TITLE
CMS 5 - Registered MFA methods no showing in SecurityAdmin

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-mfa#479]
After registering TOTP in CMS 5 - I cannot see it in Security Admin

![image](https://user-images.githubusercontent.com/4809037/213031093-eeb5f4a0-3731-4685-ab51-00d19fd103cd.png)

**Comment by maxime-rainville** [comment]
Was fixed indirectly. It didn't get flag in the regression test.
