### ISSUE TITLE
Can't login when mfa is installed

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-mfa#483]
This [change](https://github.com/silverstripe/silverstripe-mfa/pull/482/files#diff-5800f875a776e201bdea90a86e3d9a0c5d18bfde1929240700d4d95b65a50293L102) caused a regression - I can no longer login to the CMS when the MFA module is installed

After I do a brand new install
When I got to /admin
And  I type my user/pass in
Then I'm redirected to where I just was

### PRs
- https://github.com/silverstripe/silverstripe-mfa/pull/484

**Comment by maxime-rainville** [comment]
All done.
