### ISSUE TITLE
Backup codes download file name is not unique

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-mfa#510]
After downloading the backup codes for multiple websites, I now have a Downloads folder full of "Recovery codes(x).txt" files.

I have absolutely _no_ clue which project/website they belong to.

Suggestion:
Name the file something along the lines of `$SiteConfig.Title Recovery codes.txt`

**Comment by GuySartorelli** [comment]
That sounds like a good idea. Would you like to raise a PR introducing this change?

**Comment by Firesphere** [comment]
No

**Comment by elliot-sawyer** [comment]
Could this be configurable by a user with a `private static`? Or maybe do what the CSV exporter does - append a timestamp

**Comment by michalkleiner** [comment]
At a glance, the complicating factor here might be that the filename is not coming from the back-end but it's created in the react component, so it's not as easy as adjusting the PHP code.

**Comment by GuySartorelli** [comment]
Sounds like this will be fairly complex to implement, and there's no indicated desire from anyone to actually implement it.
As per [our contribution guidelines](https://docs.silverstripe.org/en/5/contributing/issues_and_bugs/#feature-requests) I'll close this for now, but if someone wants to give this a go I'd be happy to reopen it.

The simple workaround is to manually rename the file after downloading it, which is probably good advice anyway.
