### ISSUE TITLE
TODO: Implement methods in test classes

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-mfa#512]
## Description
The following classes have unimplemented methods:
- SilverStripe\MFA\Tests\Stub\Null\Method
  - getThumbnail
  - applyRequirements
  - getUnavailableMessage
- SilverStripe\MFA\Tests\Stub\Null\RegisterHandler
  - start
  - register
  - getDescription
  - getSupportLink
  - getSupportText
  - getComponent
- SilverStripe\MFA\Tests\Stub\Null\VerifyHandler
  - start
  - verify
  - getComponent 
  
We are using these classes only for testing.

**Comment by GuySartorelli** [comment]
Given the tests are passing, I'd say it's fine to just leave these unimplemented.
