### ISSUE TITLE
TODO: Define the default value for Default Registered Method as fallback.

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-mfa#514]
## Description
We should define Default Registered Method as fallback if registered method no method is specified.
See https://github.com/silverstripe/silverstripe-mfa/blob/3a59622460d4c59630b07ee294bee698ccba6ceb/src/RequestHandler/VerificationHandlerTrait.php#L45-L48
and 
https://github.com/silverstripe/silverstripe-mfa/blob/3a59622460d4c59630b07ee294bee698ccba6ceb/client/src/components/Verify.js#L48C7-L55

**Comment by GuySartorelli** [comment]
Isn't that what this code is already doing? If there's no registered method, it uses the default.

**Comment by GuySartorelli** [comment]
Closing as my understanding is that this is working as expected.
