### ISSUE TITLE
"session timed out" login dialog needs to works with MFA

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-mfa#52]
We need to ensure that the login popup you get when you've logged out due to inactivity still works with MFA.

You can reproduce by logging out in a new tab then clicking on a page in the site tree.

Notes:
- Requires the MFA modal or Sudo mode first

**Comment by brynwhyman** [comment]
@silverstripeux can we please have a chat and talk this one out? Would we assume password and/or MFA is required here?

**Comment by newleeland** [comment]
From the planning meeting it was discussed that requiring password and MFA to reactivate the session after session timeout might be a little complicated to do, as in addition to entering the password, the user would be taken to a new page and required to validate their MFA before being redirected back to where they left off without clearing any unsaved changes they may have.

An alternative option was to not have MFA on session timeouts, using only the password, as it can be assumed that the user had to enter MFA verification to get into the CMS in the first place.

**Comment by robbieaverill** [comment]
Seems to be working for me with the following steps:

* Log in
* Perform MFA verification
* Go to the Pages section
* Open the logout link in a new tab and close it
* In the original tab, click on a page in the site tree
* Re-authentication dialog shown, enter password and "Let me back in"
* Continue to navigate the CMS successfully

It shouldn't prompt you for MFA at this point, and doesn't appear to be doing so.

@brynwhyman do you agree?

**Comment by ScopeyNZ** [comment]
Do you just want to double check that a user can't change the request payload when "resuming" to get around MFA (given they know someone elses password). The original concern was that the client sent through a member ID or something when "resuming" the session.

**Comment by robbieaverill** [comment]
The user is assigned a `tempid` token, which is used to identify them which lasts for 72 hours by default. It then proceeds to compare the password you provide against a Member it finds with this token. TBH I think the security aspect of this part of silverstripe/framework should be discussed via the security mailing list if it were scrutinised and found to have defects.

**Comment by brynwhyman** [comment]
Thanks for reviewing this @robbieaverill, I had been thinking of previous discussions where we thought we might want to implement MFA into the session timeout dialog. Closing this issue as "investigated with no further action required".

**Comment by ScopeyNZ** [comment]
Sounds good to me. I think this can be closed then.
