### ISSUE TITLE
MFA should be taken into consideration with account lockouts

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#53]
Given that a certain amount of failed login attempts will lock an account (and log this in the CMS), failed MFA logins should also be taken into consideration and lock an account if the maximum failed attempts are reached.

**Comment by robbieaverill** [comment]
When we do this we should try and re-use the core "login attempts" API if possible.

**Comment by brynwhyman** [comment]
Closed for #47
