### ISSUE TITLE
User can define primary method

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#66]
As a CMS user who has multiple registered MFA methods, I want this ability to set a primary method, so that the next time I log in I am presented with my primary method as the first option.

**ACs**
- The CMS user has the ability to do this in the CMS
- Configuration in the CMS to set a primary method will be available for all methods that are currently registered and not the primary for the user
- The first method to be registered will by default become the primary, unless changed by the CMS user.

**Designs**
- https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/321186220

**Comment by brynwhyman** [comment]
@silverstripeux I have some questions about the designs for this issue. For methods that are not a primary method, you have the option to "Set as a primary method", but how does the user know what their current 'primary method' is? 

I'm guessing it may be covered by the method that has "(default)" in the title, but without using the same term, i.e. primary vs default, I find it a little confusing.

**Comment by newleeland** [comment]
Good spotting! I think we Should use consistent terminology. We could rename **primary** to **default** e.g. "Set as primary method" to "Set as default method".

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-mfa/pull/205
