### ISSUE TITLE
Changes to user's MFA should result in email

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#67]
As a user with a registered MFA method, I would like to receive email notifications for all updates related to my MFA, so that if I receive an email referencing a change I am not aware of I can expect my account to be compromised and follow the recommended steps. 

**ACs**
- Any actions changing or resetting authentication mechanisms will trigger automated emails to the email address of the user
- Email should make specific reference to the MFA method
- Email should provide steps for the user to take if the change was not expected
- Email template is theme-able 

**Notes**
- Examples of changing or reseting:
a. MFA method is registered
b. MFA method is removed
c. Recovery codes are reset
d. Recovery code is used
e. One recovery code left?

**Comment by brynwhyman** [comment]
Comment from #25 (when you almost run out of backup codes):

> @robbieaverill : I think an FYI email might be a good idea, perhaps saying "please log in and reset your backup codes if you'd like to generate a new set" or something like that (wording TBC).
We could either do this with queuedjobs or with an extension point in the login process, but either way we'd probably only want to notify the user once (?) rather than every time they login, or the job runs.

**Comment by brynwhyman** [comment]
Relevant core issue here: https://github.com/silverstripe/silverstripe-framework/issues/8594

**Comment by robbieaverill** [comment]
Example "e. One recovery code left?" - I thought there was a separate issue for that. I think it must be https://github.com/Firesphere/silverstripe-bootstrapmfa/issues/11 which hasn't been brought over to this repo. Either way I think we should treat it separately to this issue.

**Comment by brynwhyman** [comment]
@robbieaverill 
>  I thought there was a separate issue for that

It was covered in #25 but I closed it for this one. I'm happy for you to reopen that issue if it makes sense to handle it separately.

**Comment by brynwhyman** [comment]
Moved back to Ready and removed @NightJar's assignment. Not sure what progress was made, but might be worth checking with NightJar
