### ISSUE TITLE
'Keep me signed in' extends to MFA

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#70]
Expect we'll get this for free, but raising here so it's not lost.

Users already have the option to remember their login for x days on devices they trust, as an opt-in feature on the login form. This behaviour needs to be extended to MFA.

AC
- A user with a registered MFA method who selects the 'Keep me signed in' option at the login form screen will not be prompted to log in with MFA on the same device within the configurable amount of days.

**Comment by ScopeyNZ** [comment]
I can confirm that we "get this for free" :) - Should we leave it open for a future A/C check?

**Comment by robbieaverill** [comment]
We get it for free, no need to keep an issue open for it
