### ISSUE TITLE
Increase strength of recovery codes

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#71]
The current implementation of recovery codes is too weak (six numeric characters). The entropy needs to be increased. 

ACs
- Generation of codes meets the requirements laid out in [NIST Special Publication 800-63B Digital Identity Guidelines](https://pages.nist.gov/800-63-3/sp800-63b.html), 5.1.2 Look-Up Secrets
- Meets the requirements laid out in the internal SAD, 4.5.4 Cryptography and Security
- Increasing the default amount of recovery codes generated has been investigated and a decision made
- It has been considered whether new a 'recovery code' graphic is needed (current one only show six asterisks)

**Comment by brynwhyman** [comment]
@silverstripeux, FYI:
> It has been considered whether new a 'recovery code' graphic is needed (current one only show six asterisks)

**Comment by clarkepaul** [comment]
9 would be pretty standard right?

**Comment by robbieaverill** [comment]
Relevant excerpt from NIST: "Look-up secrets SHALL have at least 20 bits of entropy." From the internal SAD: "The backup codes are generated as alphanumeric strings with mixed case and a length of six characters."

With a six character length and only using digits we'd be using ~10 bits of entropy. Using a mixture of letters and numbers at six character length would be ~20 bits and using mixed case letters would be 24 bits.

If we use nine characters of digits and mixed case letters we'd have ~38 bits of entropy. This would satisfy both cases. Happy with that @brynwhyman?

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-mfa/pull/91
