### ISSUE TITLE
Update UI for responsive view

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#75]
**Overview**
In order to provide the best UI for reduced screen sizes, some changes to the existing UI could be made.

**Tasks for mobile view**
- [ ] Remove registration method graphics, stack options vertically one option wide
- [ ] .

**Comment by brynwhyman** [comment]
@silverstripeux I've raised this after a comment in the recent sprint demo. Please feel free to elaborate on, add graphics, etc.

**Comment by robbieaverill** [comment]
FYI we are building with responsive views in mind as we go

**Comment by clarkepaul** [comment]
Unfortunately, we won't be going through and designing each screen for mobile as it would be too time-consuming. What works well is doing best effort as part of developing for desktop, and for tricky views we'll come and sit with the dev to work through the views and any issues we find. If a view is particularly complicated we will provide mockups on request.

**Comment by robbieaverill** [comment]
I think we can close this for now since we're doing it as we go. If specific issues are found we can raise bugs for them.
