### ISSUE TITLE
Handle unavailable method in more options screen

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#81]
**User story**
As a user trying to verify through the 'more options' screen, I want to know if an authentication method is not available based on my browser requirements, so that I don't select an option to verify that won't work in my scenario.

**ACs**
- A user trying to use this method in the MFA flow is given information as to why it won't work with their browser, and is blocked from using it
- Methods that are unavailable are disabled from selection

**Notes**
- This issue focuses on styling
- Unavailability (based on browser requirements, etc) should be defined by the method module in
- Design of screen in question (without the required styling): https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/321189140
- Note that this is different from #77

## Pull requests

- [ ] https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/27
- [ ] https://github.com/silverstripe/silverstripe-mfa/pull/199

**Comment by newleeland** [comment]
@robbieaverill I've updated the above link to have to include a solution for unsupported browser i.e. security key. Basically, it allow user to click, but opens tooltip informing the browser being unsupported.

**Comment by ScopeyNZ** [comment]
If security key is their primary authentication method, should we default to the select method screen when they're using an unsupported browser?

**Comment by robbieaverill** [comment]
IMO yes of there’s another method, and if not then straight to backup codes with an info message displayed

**Comment by brynwhyman** [comment]
@newleeland we won't be implementing the tooltip as part of this

**Comment by newleeland** [comment]
> @newleeland we won't be implementing the tooltip as part of this

From the talk during the grooming session, I was thinking of looking into tweaking the current design slightly so that the text is more legible rather than taking more effort implementing the tooltip.

**Comment by robbieaverill** [comment]
I don't think the designs reflect what screen we're talking about here. It's this one:

![image](https://user-images.githubusercontent.com/5170590/58529412-b814fb00-822e-11e9-948e-0fb5b034dc3a.png)

Correct me if I'm wrong @brynwhyman

**Comment by robbieaverill** [comment]
@newleeland see https://github.com/silverstripe/silverstripe-mfa/issues/77

**Comment by brynwhyman** [comment]
That's correct @robbieaverill , I've changed the designs back.

This screen doesn't have designs yet, but it needs to disallow methods from the 'more options' screen for browsers that do not support it

**Comment by newleeland** [comment]
I've updated the design what unsupported options

**Comment by robbieaverill** [comment]
PRs in the description
