### ISSUE TITLE
Add flexibility in how MFA should be applied to users

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#89]
**Overview**
Currently, MFA is being built to apply to all site members. If someone was using SilverStripe for frontend user management (outside of the CMS) the current implementation would require MFA for those users too.

This may be seen as an unwanted feature.

**User story**
As a site developer, I want the ability to choose whether MFA should be applied to accounts used only for frontend user management, so MFA is not made a requirement for site members with little security/access scope.

**ACs**
- The requirement for MFA by a member can be tied to their user permissions. I.e MFA can be limited to 'has CMS access'

**Notes**
- I've written this from the perspective of a developer given this would probably be a decision made during development and less likely to be retroactively configured by a CMS admin.

**Comment by newleeland** [comment]
Would we want to consider websites that don't have a CMS just a frontend portion ()?
This would influence how the MFA would be managed (e.g. from the CMS UI and/or Frontend UI)
If MFA was enabled on both Frontend and CMS do we want them to have the same MFA settings (i.e. MFA is Optional) or would we want to separate settings

**Comment by ScopeyNZ** [comment]
1) Yes. The A/C ensures that it can be limited to "CMS access" but I don't think it should be limited to that. That is a sensible default though. 

2) It's definitely a valid use case that you'd want this to be controlled differently. It should probably be a separate issue though.

**Comment by newleeland** [comment]
> 1. Yes. The A/C ensures that it can be limited to "CMS access" but I don't think it should be limited to that. That is a sensible default though.

I'm just thinking of how an admin would manage their MFA configurations. Their FE UI might be setup differently to how we have it in the CMS. We might have to create our own UI (e.g. a modal), as the existing UI may not fit every unique FE. That is why the MFA for DASH is custom design to its layout.

**Comment by ScopeyNZ** [comment]
So we provide the ability to implement the consistent UI element as it's own component. You should be able to integrate this into what ever UI you have. This should support dash easily. This story is about ensuring the permission side is permissive enough.

**Comment by brynwhyman** [comment]
To clarify, the AC covers "The requirement for MFA by a member can be tied to their user permissions." - limiting to CMS access is just an example.

I've raised a separate issue to cover the below, here: #179. Please check if that covers your expectation.
> If MFA was enabled on both Frontend and CMS do we want them to have the same MFA settings (i.e. MFA is Optional) or would we want to separate settings?

**Comment by brynwhyman** [comment]
This is pretty related to #179.

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-mfa/pull/197
