### ISSUE TITLE
New user permission 

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#90]
There is a new group/user permission created for accessing important MFA settings what could be classed as elevated admin permissions for MFA, e.g.
- enabling/disabling MFA for a site
- resetting another users MFA credentials (#40)

**Comment by robbieaverill** [comment]
Would it be used to control whether you can access your own MFA settings, or other people's MFA settings? I think we can easily say that "admin" permissions are required to access other people's settings, maybe we don't need a new set of MFA permissions

**Comment by brynwhyman** [comment]
This issue was raised to cover what could be classed as elevated admin permissions for MFA, e.g.
- enabling/disabling MFA for a site
- resetting another users MFA credentials (#40)

_Updated the description._
