### ISSUE TITLE
Registration flow: What to do if no method is correctly configured?

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-mfa#93]
Given there a site has `silverstripe/mfa` and a single Method are installed
And **the method is misconfigured**
And MFA is mandatory, with no grace period
And a user attempts to log in without having the MFA method set up
And they have accepted the "get started" button from the MFA info prompt
Then ??????????????

@brynwhyman 
@newleeland we need your help :)

Currently this happens:

![image](https://user-images.githubusercontent.com/778003/56183431-a99dc600-606a-11e9-918f-df73fdcc7e94.png)

Which isn't so bad, but could use some UI adjustments.
But if #92 is complete then this will no longer happen.

**Comment by robbieaverill** [comment]
This could still happen. #92 is done, but if the only method available is disabled due to environment conditions (like running an unsupported browser) then you'd still see this screen.

Re-bump @newleeland @brynwhyman for feedback.

IMO this screen is fine as is, but would be good to get some actionable points for this issue.

**Comment by robbieaverill** [comment]
Wrong button

**Comment by newleeland** [comment]
Hmm. I've got a few questions,
1. How does a user end up getting **the method is misconfigured**?
2. What causes it?
3. Is it specific to all methods or just selected methods

**Comment by robbieaverill** [comment]
Here's a simple scenario:

* You install the MFA module
* You install webauthn
* You access the site over HTTP (not HTTPS)

You'll only have the webauthn authenticator available to use, but it's disabled because you're not on HTTPS.

**Comment by brynwhyman** [comment]
I think as a first point of call, we should make sure that the back button is available regardless, that way if MFA wasn't mandatory they could go back and skip the process - I've raised a separate issue for that here: #176

I'm not sure on further actions though. In @robbieaverill's scenario above, the messaging should be helpful enough for the user to access the site again over HTTPS. In other scenarios it seems like a case of good messaging if the browser is unsupported to direct the user to more instructions; or adequate testing and knowledge of users by those developing and selecting methods to install.

Happy to keep this issue open and seek other thoughts.

**Comment by robbieaverill** [comment]
I don't think there's any actions for this issue to keep it open. We'll ensure the back button to intro screen works via (#176) (I suspect it already does), and the wording will explain why that's the case. I don't think it's feasible to provide a way in, other than "skip" if it's already allowed, for situations where the auth methods are not available.

The login flow already handles this situation like this:

![image](https://user-images.githubusercontent.com/5170590/59736452-c7c3b480-92ad-11e9-8fe6-31e921ffd5df.png)

In the same respect, you're stuck if you can't log in from IE10, security keys is your only option, and you don't have your backup codes on you. That's MFA.

**Comment by robbieaverill** [comment]
Reopen if you think there's actionable points left on this issue
