### ISSUE TITLE
Registration flow: Disable next button until a method is selected

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-mfa#94]
Currently when a user logs in and is prompted to register for MFA, they are presented with a selection of enabled methods. The next button is enabled and it is not obvious that the user needs to select an option. This could be made more obvious by
a. disabling the next button until an enabled method is selected
b. dispensing with the next button entirely and simply activating the method when the user clicks on it. There is a back button on the following screen that the user could use to return to choose again if they wish.

**Comment by NightJar** [comment]
@newleeland guidance please :)

**Comment by robbieaverill** [comment]
@NightJar I don't think this is true, can you confirm that the next button is disabled until you've selected a method?

**Comment by NightJar** [comment]
No longer an issue as at b610445e1c96e40df18c0ee57859eea2e92bc361
