### ISSUE TITLE
Accessing the MFA route directly should redirect you away if MFA is disabled

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-mfa#98]
> Question: when you hit the MFA endpoint directly when MFA is not enabled, what should happen? Currently it shows the MFA form. I guess it should redirect to Security/login instead?

( https://github.com/silverstripe/silverstripe-mfa/pull/97#issuecomment-483889543 )

**Comment by robbieaverill** [comment]
We're going to remove the option to disable MFA, right? It's always enabled if the module is installed, but can be optional?

**Comment by ScopeyNZ** [comment]
Good point. I'll close this in favour of that (#144).
